### ISSUE TITLE
DANCE TERM SUBSTITUTION

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#100]
User-defined substitutions for hot-topic contra terms. 
- [x] 'gyre*' moves to whatever
- [x] 'ladle' to whatever
- [x] 'gentlespoon' to whatever
- [x] arbitrary moves and whos? e.g. "ones" => "twelves"?
- [x] also search notes? Yes: users love to talk about ladles in notes.

**Comment by cranhandler** [comment]
- [ ] petronella to whatever
- [ ] Rory O'Moore to whatever
- [ ] 'swat the flea' called box the gnat by left
- [ ] 'see saw' called do-si-do by left
