### ISSUE TITLE
0 beat figures don't print as "for 0"

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#134]
That's surprising to me, since if a move isn't 8 (or whatever it's default is), it prints as "for X". 

Maybe it's because 0 is false in javascript, at some point in the decision chain?

It's not intended, but is it a feature? It comes in handy for, e.g., progression. I've actually never been annoyed by it, just surprised.

**Comment by dcmorse** [comment]
I feel it's a feature.

**Comment by cranhandler** [comment]
I might have re-found the incorrect issue, but I recalled an issue where we didn't want "for X" beats to _ever_ appear in the text of the dance. We were going to have a little prefix between the A1 and the figure itself. 

A. O. 's No-No is a star pupil for being almost illegible when it has 'for 2" and "for 12 " everywhere in it. 

It could also be a star pupil for "other than half or whole" heys being enabled using the "X starts by X shoulder until" model... but I know that's a harder sell. The dance would at least  be legible if we stopped printing beats.

**Comment by cranhandler** [comment]
http://contradb.com/dances/350

This dance is ALSO a case for Cary Ravitz's "0th neighbor" or having 'original neighbor' display.

**Comment by dcmorse** [comment]
I feel like you want to make a "A.O.'s No No" issue. :D 

I'm going to break your issues into three different areas. 

1. *for x beats* the issue you're looking for is #228, and you prioritize it highly, so it should theoretically be done 'soon'. 
2. hey-until #290
3. `neighbor` to print as `original neighbor` #291

Since this current 'issue' is actually a special case 0-beat-only implementation of #228, I'm closing this issue.
