### ISSUE TITLE
ocean wave

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#137]
Someone wants to rename "ocean wave" to "to ocean wave" so it is a "verb". 
UPDATE: Someone just wanted the figure to print "to ocean wave", but the move to still be named "ocean wave", which makes more sense and is a smaller change.

**Comment by dcmorse** [comment]
List of alternatives

- `ocean wave`
- `to ocean wave`
- `melt into ocean wave`
- `smush into ocean wave`
- `short wavy lines`
- `to short wavy lines`
- `melt into short wavy lines`

To me `ocean wave` implies a certain way of arriving in short wavy lines.

**Comment by dcmorse** [comment]
b7aaffb465285ecc840b793ab07f485c8c285784

**Comment by cranhandler** [comment]
Could 'to ocean wave' be a potential dropdown item for 'allemande' and 'pass through'? 

As in, 'turning' parameter options include 1, 1 1/2, 2, to ocean wave, to long waves
?

**Comment by dcmorse** [comment]
Thank you for continuing to beat drums on this. 

I've intended the figure `to ocean wave` to imply `pass through to an ocean wave`, that is, a particular flight path that's sort of cross-trails-esque. That should handle the 'pass through' half of this request. Maybe it should still print as "pass through to ocean wave", "melt to ocean wave" or something. 

As for the allemande, what's wrong with using `partners allemande left once` note: `to short wavy lines`? It seems to me like that's a perfect use of a per-figure note.

**Comment by dcmorse** [comment]
@cranhandler, I still think the allemande left once should simply have a note `to short wavy lines`, and leave ocean wave out of it. 

(Closing for lack of response - reopen if you want)

**Comment by cranhandler** [comment]
The figure "ocean wave" with print text "to ocean wave" is working quite nicely. 

"to ocean wave [and | , ] balance the wave" is a common 4 beat and 4 beat couplet.
Would it make sense to have a "balance" checkbox that could be filled out for this? 
Currently I'm making the next figure a "balance ; everyone ; 4 beats" and that reads fine, although on a separate line.

Potential issue with doing this is that usually that checkbox is meaning "balance then [figure]" rather than "[figure] then balance" 

See "A 60th Birthday Dance" as one example.

**Comment by cranhandler** [comment]
Here is input from Myra Hirschberg, when asked what she would have searched for since she didn't find "to ocean wave" 

> As a caller or when I write out cards, I usually just say “step into a wave across” (or “long wave”).

**Comment by dcmorse** [comment]
Great. Let's put this at the top of the list. I can do it in my sleep.

**Comment by dcmorse** [comment]
Okay @cranhandler, the code support is there. Please update eligible dances.

**Comment by cranhandler** [comment]
In progress. Struggled with:

http://contradb.com/dances/102/
