### ISSUE TITLE
Up and down the hall: cloverleaf ending

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#166]
In http://contradb.com/dances/100 , 

Cozy Line
Cloverleaf
Turn Out Of Cloverleaf (don't know the name for this one, personally) 

are all used as modifiers for up/down the hall.

**Comment by cranhandler** [comment]
Another 'down the hall' ender is "thread the needle" 
(all four hold hands, Gents on end make arch with neighbor and
lady on the other end go under arch while gent on end walks around to invert the line
(couples change sides of the set)—lady in the middle twirl under her arm—and face up)

**Comment by dcmorse** [comment]
I don't understand the description. "All four hold hands" makes it sound like the line has already bent into a ring, at which point wouldn't this be a new figure?

**Comment by cranhandler** [comment]
No, this is the one that is called in STL more like 

"Right hand high, left hand low" (which is a call to the gent. It means:

all four dancers are in the line having walked "down the hall" G L G L line
Gent raises his right hand (arch with neighbor ladle) and lowers his left hand (partner ladle dives through the arch) 



Wow, no it's not. 

This is 
G1 L2 G2 L1 down the hall

G1, the only "end gent", makes an arch with L2
L1 lets go of G2 hand, goes under the G1-L2 arch 
G2 shuttles  around  to the other end

now 
G2 L1 G1 L2 line up the hall

**Comment by cranhandler** [comment]
Anyway, proposal of 
- thread the needle
- right hand high, left hand low

both being added as "down the hall / up the hall" enders. Proposal implies that a caller not call dances with these "enders" unless they know how to describe them. (count me out!)

**Comment by cranhandler** [comment]
Another "down the hall" ender: 
sliding doors

Sliding doors (trade places as couples and turn alone) (4) (as in Rick Mohr 'Tag and Zag')

**Comment by dcmorse** [comment]
## Actionable:
1. Cozy Line
2. Cloverleaf
3. Thread the Needle
4. Right Hand High, Left Hand Low
5. Sliding Doors

**Comment by dcmorse** [comment]
Note that Lynn and I couldn't figure out what to make of "Turn Out Of Cloverleaf (don't know the name for this one, personally)", so she did nothing in #281

**Comment by dcmorse** [comment]
Lynn's done the coding. @cranhandler can you adopt this in your dances now?
