### ISSUE TITLE
arch & dive

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#210]
Parameters
Who makes arch (ones, twos, inside couple, *)
Who dives (ones, twos, outsides, those alone) 

custom move in
http://contradb.com/dances/161

*I'm not sure if you need to list out
Gent 1 lady 2
Gent 2 lady 1
or Gent and RH lady 
Gent and LH lady

or what others?

**Comment by dcmorse** [comment]
This is in a square-ish formation, right?
Is the direction of movement always up/down the set, or can it be across?

**Comment by cranhandler** [comment]
Yes, squarish. Both are possible, also scatter mixers are possible (but
that can be handled in 'note' I think?)

**Comment by dcmorse** [comment]
Do we have any dances with it being across the set? If not, let's keep it
longitudinal for now?

Remind me to say the "rule of three"

**Comment by cranhandler** [comment]
The across-set example I've danced was called by Susan Kevra in Urbana. I
don't have its name right now.

**Comment by dcmorse** [comment]
If we leave it dancer-based, then I guess we don't need to encode the set direction. Someone will inevitably request it, and then we'll have stressful debates. Sigh. But since most are along the set, let's postpone those stressful debates for later.

**Comment by dcmorse** [comment]
I think the subject menu will include:
```
                    ['gentlespoons',
                     'ladles',
                     'ones',
                     'twos',
                     'first corners',
                     'second corners']
```

aka `chooser_pair`. That's every possible combination, I think.

**Comment by cranhandler** [comment]
I found once dance ( http://contradb.com/dances/319 ) which would benefit from the "who" param including "outsides" and "insides".

This one is in fact a square dance so we don't need to address the issue at this time.
