### ISSUE TITLE
up and down the hall: rename to 'march"?

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#226]
is the proper name of `up the hall` and `down the hall` actually `march`? That'd coalesce two figures that should basically be the same thing.

**Comment by jmdyck** [comment]
Or "go", or "walk".

**Comment by dcmorse** [comment]
Those are all fine synonyms for the spoken word, but also the name of moves is governed a little bit by what people might guess in terms of alphabetical order. That's one reason the off-color-dad-joke of a move name 'gyre' has held on so long. 

'go' and 'walk' have so many synonyms, that I think people'd have trouble remembering the word and thus scanning for it in a 50-element menu. "March" has that problem less, because it's a specific and anomalous means of moving. Also, it compresses two moves down into one, making all moves that much easier to find. 

But I don't know if anyone actually thinks of it as a "march" besides me.
