### ISSUE TITLE
figures never say how many beats they are in prose

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#228]
this discussion started like so
# 'custom' figure should not display beats regardless of number of beats
Displaying [ * ] for 4 is undesirable. If I am writing a custom figure I will specify all the language I need, I am only entering a number of beats so the dance will compile. 

Example in A2 of http://contradb.com/dances/196

**Comment by cranhandler** [comment]
Broadening to all figures: I don't want to see the number of beats, even if it's unusual. Example
http://contradb.com/dances/203

maybe there can be a 'suppress beats' checkbox which is by-default checked in all cases, that people can uncheck if they desire for an unusual circumstance?

**Comment by dcmorse** [comment]
- [ ] change dance editor to display a beats column
![ss](https://user-images.githubusercontent.com/10550086/33516341-02d9c958-d737-11e7-8bf3-666be0169af4.png)

- [ ] simply remove beats from display of dances - except maybe on mad-robin and half-pousette - the oddball moves that work best at 6 beats. 

- [ ] mull a per-user or per-dance preference to display beats in dances.

**Comment by dcmorse** [comment]
Implementation idea: sbeats is always 0, in a stroke zapping most problems. [2]
Implementation idea: rip it out the right way, thus vastly simplifying the hairiest dance views. [3]

In any case, revise the spec first.
