### ISSUE TITLE
Split About box into About and Help

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#249]
About box tells about the application.
Help page links to email addresses, and also wikis. Email addresses are only visible to logged in users. 

The current about box copy taunts by talking about live help, but provides no links to it. 

The dance editor provides a link to talk to admonsterator. This can be removed at the end of this story, or redirected to adminisaur.

**Comment by dcmorse** [comment]
#273 partially addresses this.

**Comment by cranhandler** [comment]
Help page brainstorming. My 'aesthetic' suggests one page with a category-type index which jumps you down the page to your area of interest. I assume we will actually want to be more lean than my aesthetic. 

-why are we here?
link to about page

-how do I enter a dance? 
link to youtube video from https://github.com/contradb/contra/issues/296

-how do I search for dances?
link to youtube video 

-how do I create a program?

-can someone talk me through this?
adminisaur(adminisaur@contradb.com) is happy to screenshare with you through a dance entry learning process. 

-something is broken.
admonsterator made this site. [Contact him](admonsterator@contradb.com) or use 
        <a href="https://github.com/dcmorse/contra/issues">github</a> to discuss bugs.

-a dance I wrote is mis-entered, my name is misspelled, or I would like my dance taken down.
adminisaur keeps our data clean and consensual. [Contact her](adminisaur@contradb.com) to add information to a choreographer page representing you.

-what are contradb.com's dance publishing ethics?
link to nested help page

**Comment by dcmorse** [comment]
## WIP
I think these are all ready to go, except the 'Help' page, which is still being HTML-typeset. 
![2](https://user-images.githubusercontent.com/10550086/36795036-93e778da-1c67-11e8-85b5-df39062237d1.png)
![1](https://user-images.githubusercontent.com/10550086/36795044-987dd754-1c67-11e8-863a-e0b5f86a12f1.png)
![3](https://user-images.githubusercontent.com/10550086/36795058-9f75546a-1c67-11e8-8ffb-82aa6116137b.png)

**Comment by cranhandler** [comment]
Two minor edits:

in Help
'link to nested help page' to be replaced with
'we're currently gathering community input, please [participate](https://github.com/contradb/contra/issues/297) '

in About:
'future you will be able to' to become 'future you will _also_ be able to'
then drop the first two bullets because they can be implied.

**Comment by dcmorse** [comment]
We all have to remember to update these pages. Especially for the 'we're currently gathering community input, please participate' link. 

I'm setting up a calendar reminder to audit them every other month.

**Comment by dcmorse** [comment]
![3](https://user-images.githubusercontent.com/10550086/36829138-43580174-1ce3-11e8-8753-18d815a4617e.png)
Is it intentional to start out a paragraph with "Future you will also be able to"?

**Comment by dcmorse** [comment]
I found a gem to keep our email addresses always clickable, albeit not always visible.
