### ISSUE TITLE
dance term aliases - term alias editor

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#261]
On the user's preferences page, there's a big "Add Alias" button. If they click it, into-existance pops a well  with a select box and a text field. They pull down the term they want from the text box (e.g. gentlespoon) and they then fill in the blank with 'lark'. Clicking submit saves preferences. 

Part of #100 
Assumed to be built atop #263

**Comment by dcmorse** [comment]
# UI
- [ ] In the logged-in user menu in the upper-right, add a menu item 'Preferences', which goes to /preferences/edit
- [ ] for each move and dancer, there's a line where they can fill in a blank. That's the new substitution. Entries that are all whitespace are compiled out of the list. There is a submit button.
- [ ] on each figure page, it displays both the term and substitution, leading with the substitution. If there is no substitution, display the term itself.

**Comment by dcmorse** [comment]
New wireframe - request for comments:
![dialect](https://user-images.githubusercontent.com/10550086/36937617-bc5a9042-1edb-11e8-8f32-cdc06dc62294.jpg)


* For switching role names to the most popular substitutions, you hit a button and are done. 
* For redefining `gyre`, you type in a field and then it saves when focus leaves the field. 
  * If you put in "turn by the", then it will correctly render "turn by the left shoulder", but will just print "turn by the " for right shoulder gyres. Check the "print right shoulder" to force it to say "turn by the right shoulder".
* when you use the above buttons, it adds terms to the main list (here represented by "slice" and "gyre meltdown").
* when you edit things in the main list, there is no dialog box. You just edit text.
* When you hit the "select dancer" or "select move" dropdowns, anything you choose is added to the main list. 
* when you hit the big red `Restore Default Dialect` it blows away all entries in the main list. 

## Look Ma, no Submit Buttons!

Instead of a submit, we make extensive use of a green circle. It's used next to all text fields, and also in the role buttons.

Next to text fields, the green circle turns yellow when they edit the text field. When focus leaves the text field, it turns to orange. When the server responds that the change is saved, it turns green again.

Next to the role buttons, the green circles are actually invisible most of the time. They turn turn yellow when you click the button, and green when the server responds success. As long as you keep the (large number) of idioms they set undisturbed, that one button will remain green. If you disturb the balance in the low level editor, say by choosing Larks and Ladies, then the green circle disappears. 

Next to an X (close) button, the green circles go yellow when you click, and then green when the server responds success. Next to an item in the main list, when the server responds success the list element is also deleted, so you don't see that much. Maybe a flash message "deleted 'slice' idiom" would be in order here.

**Comment by cranhandler** [comment]
This looks functional, I want to check, though---does this stronger framework for our commonly expected substitutions still allow for optional, non-expected-by-the-devs substitutions at a user's option?

**Comment by dcmorse** [comment]
Yes.

Note that you may expect clicking  'ladies & gents' will add two entries to the main list, but in fact it adds *six*: 
* gentlespoons -> gents
* ladles -> ladies
* first gentlespoon -> first gent
* first ladle -> first lady
* second gentlespoon -> second gent
* second ladle -> second lady

Whoops, the Gyre stuff doesn't work. Back to the drawing board on that. 



(again, main list happens to have 'slice' and 'gyre meltdown' in the image above, but will grow/contract based on how many idioms the user has).

**Comment by dcmorse** [comment]
well, what we delivered was a lot different than this, but better. Woo!
