### ISSUE TITLE
Ask choreographers for permission to publish dances

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#267]
##Originals
- [x] Bob Green-[x] AJ text
- [x] Jim Hemphill-[x] AJ text
- [x] John Coffman -[x] AJ email
- [x] Sarah Kaiser-[x] AJ email
- [x] Dale Wilson -[x] AJ verbal
- [x] Yoyo Zhou -[x] AJ DM email
- [x] Cary Ravitz -[x] DM facebook message
- [x] Dan Pearl -[x]
- [x] Done Veino -[x] "sometimes" 
- [x] Eric Black
- [x] Linda Leslie

## American Week List
- [x] Paul Wilde (AJ emailed on 2017 12 15) 
“This dance is dedicated to the memory of Jeff Ratsch, a great friend, dancer and human being. He
brought out the best of us in so many ways. Dance this one for Jeff, and for all of us.”
Paul Wilde

## Chet's NYE program
- [x] Ron T Blencher -[x] AJ facebook message http://contradances.tumblr.com/dances  - my dances online. I'm fine with anything I've published being republished on not-for-profit sites.
- [x] Grant Goodyear -[x] AJ email
- [x] Lynn Ackerson
- [ ] Becky Hill (assigned to Dave)
- [x] Tony Parkes
- [x] Nils Fredland - [x] AJ facebook message
- [x] Bradley Smith - [x] AJ text
- [x] Ron Buchanan
- [x] Bob Isaacs
- [x] Myra Hirschberg - [x] AJ facebook message

## Misc
- [ ] Lisa Greenleaf (assigned to Dave)
- [x] Jerome Grisanti (assigned to Dave)

**Comment by dcmorse** [comment]
I fired off a second request to Lisa Greenleaf.
I fired off a first to Jerome Girsanti
I will attempt to track down Becky Hill.

**Comment by cranhandler** [comment]
Continue to add comments as needed for new permissions.
