### ISSUE TITLE
figure search 'then' returning bogus results

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#269]
This should not be happening. There is only 1 figure between the swing in 3-33-33, not two.
![screenshot-2018-1-2 welcome contra](https://user-images.githubusercontent.com/10550086/34475583-03f5a7a6-ef53-11e7-951a-bc9ee04c1f98.png)

**Comment by cranhandler** [comment]
Is this certainly a bug of "then", as opposed to a bug of "any"?

**Comment by dcmorse** [comment]
resolved by 0f9229e66a1711e2e6288276f6f3067fa2a929c5
