### ISSUE TITLE
Pousette

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#271]
I can't find a lone "pousette" topic so I'm making one.

Why can't I say "clockwise" or "ccw" in the text, if that's what I want to encode? 

![image](https://user-images.githubusercontent.com/16180173/34499366-5e64a9c6-efcb-11e7-871e-8b1af0ef14f2.png)

might touch
https://github.com/dcmorse/contra/issues/234
and 
https://github.com/dcmorse/contra/issues/122

**Comment by dcmorse** [comment]
You're looking for #170 pous*s*ette with two `s`es. 

'Clockwise' and 'Counter Clockwise' require dancers to think about the dance from above. It's an extra cognitive step that can be trimmed from dance calls.  This compact, accessible verbiage came from Cary Ravitz.
