### ISSUE TITLE
Pinewoods American Week Dance Swap 2017

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#272]
- [x] enter all dances
     - [x] Dave to enter Can't Get There From Here
     - [x] Need to hear what to do on Paul Wilde's dance title
     - [x] Need Zig and Zag to be separate figures for Tag & Zag
     - [x] Bob Stein's square dance
     - [x] Need 'down the center' support for Star-Thru Corners 

- [x] correctly encode all "next" neighbor notes 

- [x] submit to original list to ask for input

**Comment by dcmorse** [comment]
http://contradb.com/dances/255
