### ISSUE TITLE
Formations dropdown to include 'proper'

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#295]
A fair number of contras are in 'proper' formation, yet proper does not appear in our drop-down common formations list. I petition it does. 

I have about 6 proper dances entered thus far, using all lower case proper.

Would this be something Lynn could add? And will my already-existing dances back-associate?

**Comment by dcmorse** [comment]
Yeah, it's adding an item to the right array literal. 
Once that's done, @cranhandler can manually inspect existing dances to make sure they spelled it in the canonical way.

**Comment by dcmorse** [comment]
Regarding 'back associate', yes, it's just text with heavy hinting, so if
they're spelled cannonically, they'll back associate.

**Comment by cranhandler** [comment]
Also Triplet
