### ISSUE TITLE
Dance Entry Video

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#296]
Allison has created & shared with Dave a 5:45 'how to enter a dance' video, for inclusion on the help page.
Dave to upload to youtube, clip first 30sec of false starts

Recommended Title: 
Dance Entry for contradb

Recommended description:
Learn contradb dance entry using Cary Ravitz' Heart of Glass as an example. Caller, choreographer, or dancer, add your contra dance to our live, cloud-based, crowd-sourced box. www.contradb.com

**Comment by dcmorse** [comment]
merged
