### ISSUE TITLE
Current Search Outcomes

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#301]
Some thoughts on search results that we may choose to change, or we may choose to simply be aware of as traits of our system

-searching a dance with no swings returns dances with swings encoded as gyre meltdowns. This is easy enough to fix for an experienced user (no figure = swing and no figure = gyre meltdown) but might be confusing for a new user. 

-someone may want to search, especially for a night ender, for a dance with a long swing _in the B2_. We do existence in dance and relative placement among other figures, but I don't know if we have a way to search "last figure is" or "first figure is" (or if those would be desired).

**Comment by dcmorse** [comment]
The first thing is just a thing. I find it kinda disconcerting too. I think it we should leave it be.

The second thing should be a feature request that I would be surprised if it got prioritized. There's all kinds of time masking to think about, that I'll comment on in that issue.

**Comment by cranhandler** [comment]
Hm. I think 'gyre meltdown' not counting as a swing _could actually give false negatives_. 

Say I want a dance with a rollaway and both a partner swing and a neighbor swing. There could be good dance candidates with a partner gyre meltdown, a neighbor gyre meltdown, or both, which are not returned here. If 'balance & swing' still computes as containing a swing, I think gyre meltdown should compute as containing a swing as well. 

![image](https://user-images.githubusercontent.com/16180173/36866094-f7704df6-1d56-11e8-87c7-06f48476e236.png)

**Comment by dcmorse** [comment]
Very well. 
I second the motion to make gyre meltdown count as a swing. 
Also I make a motion that see-saw counts as do-si-do. But maybe not vice versa.

**Comment by cranhandler** [comment]
Ha, you agreed before I found a concrete example. If I want a rollaway, and a partner swing but no neighbor swing, in fact Crossroads Contra passes my search criteria---but Wise People Of Chicago _actually has a neighbor swing_, it's just disguised as gyre meltdown. D:

Glad we are agreed, though :)

![image](https://user-images.githubusercontent.com/16180173/36866372-b9f98f9a-1d57-11e8-9247-76f65e6a0558.png)

**Comment by dcmorse** [comment]
I believe #306 and #128 together will address the gyre meltdown issue completely. 
The "search in B2 issue" can be split off into another issue with a better name, and this issue can be closed.
