### ISSUE TITLE
update data for figure recent tweaks

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#320]
- [x] adopt `arch & dive`, c..f. Jefferson's Remorse
- [x] use "down the center" and "down the outsides" features of `down the hall`
- [x] use "up the center" and "up the outsides" features of `up the hall`
- [x] zig zag wording is tweaked, so many instances that try to fight contradb on that can presumably stand down on their stompycaps notes now.

**Comment by cranhandler** [comment]
3 zig-zag dances viewed, notes removed, approved for publication. 

Custom moves that need to be turned into insides, outsides, or arch & dives: 
http://contradb.com/dances/402
http://contradb.com/dances/362
http://contradb.com/dances/161
http://contradb.com/dances/401
http://contradb.com/dances/396
http://contradb.com/dances/179
http://contradb.com/dances/395
http://contradb.com/dances/319
http://contradb.com/dances/244
http://contradb.com/dances/342 (email to Karl, arch & dive now supported) 
http://contradb.com/dances/233

**Comment by cranhandler** [comment]
This one is @dcmorse 's to edit http://contradb.com/dances/179
