### ISSUE TITLE
add 'gentlespoon' and 'ladle' as terms

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#348]
Principle of least surprise dictates that 'gentlespoon' and 'ladle' should translate in the right way. 

![image](https://user-images.githubusercontent.com/10550086/39095545-e3aee802-4607-11e8-918f-aecfaa3e9a01.png)
See also a desire for it in figure 8:

```

function figure8Stringify(move, pvs, dialect) {
  var [ subject,  lead, half_or_full, beats] = pvs;
  var [ssubject, slead, shalf_or_full, sbeats] = parameter_strings(move, pvs, dialect);
  var dancer_role = {'first gentlespoon': 'first gentlespoon', // wanted: => 'gentlespoon'
                     'second gentlespoon': 'second gentlespoon', // wanted: => 'gentlespoon'
                     'first ladle': false,
                     'second ladle': false};
  var tlead = (subject === 'ones' || subject === 'twos') ? dancerSubstitution(dancer_role[lead], dialect) : slead;
  var the_rest = words(tlead, tlead && 'leading');
  var smove = moveSubstitution(move, dialect);
  return words(ssubject, shalf_or_full, smove+comma_unless_blank(the_rest), the_rest);
}
```

## Research

Verify that if we have the substitution 'first gentlespoon' -> 'Larry' and the substitution 'gentlespoon' -> 'lark', that we get 'first gentlespoon' -> 'Larry' and not 'first lark'. I think that'll work. 

## Other annoying complication:
If we've got existing users using the quick-set radios, they're not going to pick up this transition. Maybe just email them individually.

**Comment by cranhandler** [comment]
Double-checking that this will include gentlespoon's and ladle's as well?

**Comment by dcmorse** [comment]
Yes. It turns out we go for straight substrings.
