### ISSUE TITLE
non-square contra dances

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#350]
Here are some dances that are more than 64 beats, and I hope the data maven can step in and fix em.

- http://contradb.com/dances/147 Reel to Reel - Chet's ancient - shouldn't be published? **
- http://contradb.com/dances/100 Monophobia - Allison's ancient - 68 beats **
- http://contradb.com/dances/211 Untitled - Karl - 66 beats **
- http://contradb.com/dances/129 The Wise People of Chicago - Chet got the math slightly wrong **
- http://contradb.com/dances/243 Spring Break (variation) - Chet got the math slightly wrong **
- http://contradb.com/dances/244 Star-Thru Corners - Allison - donno take a look **
- http://contradb.com/dances/424 Rhonda's Reel - Eric Black - just delete the trailing Empty Figure **
- http://contradb.com/dances/422 The Menagerie - Dane's WIP

**Comment by cranhandler** [comment]
All of these that were impacted by the new rollout have been corrected. Dane Wallinga's WIP didn't need changes, it's a 3-part dance.

**Comment by dcmorse** [comment]
Cool. I don't think anything changed on our side, I think it was just mistaken data entry on every users's part. (including ours).

Gotta get that beat checker back in there! #351
