### ISSUE TITLE
figure 8 again

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#353]
following the modification of figure 8 text to be hard-coded.

**Comment by cranhandler** [comment]
This is complete. About 70% of figure 8 in-line notes included 'above the twos' or 'below the ones' or some other style of 'above' or 'below.

Request adding to the figure `figure 8` the modifier "direction" where options are [ blank | above | below ] with default = blank

**Comment by dcmorse** [comment]
Thanks @jmdyck - that's the plan then:
![figure-8](https://user-images.githubusercontent.com/10550086/39194189-bfe63668-47a2-11e8-8ebe-0a1ed0526c7a.png)

**Comment by jmdyck** [comment]
Note that there's also `[half] figure eight *across*`, e.g. ["Pieces of Eight" by Peter Foster](http://pfoster.pcug.org.au/dance/contra.htm), "Old Century Reel" by Don Armstrong, "Durgin Bridge" by Bill Cochran & Al Olson, ["Precket for Kara, #1" by Erik Erhardt](https://statacumen.com/2012/05/10/contra-dance-precket-for-kara-1/).

**Comment by dcmorse** [comment]
Wow, never seen that!! Our threshold for supporting stuff is "used by 3 choreographers". We gotta have it. Thank you!
