### ISSUE TITLE
programs index displays dance and note

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#359]
I know we're not content with 'programs' in their current form, and a major revamp is to be considered and performed "some time". In the meantime, though:

The most common use for programs right now is Caller's Choice programs (often by Chet or me). Right now, when I have the person calling in the notes, the caller responsible for the slot displays... _until I enter the name of the dance_. So here I have Martha calling Parkay and myself calling Fairport Harbor, but that info is obfuscated. 

Would it be a 1 or a 2 to have this 'quick summary' include the 'note' column text? 

![image](https://user-images.githubusercontent.com/16180173/39492101-19afc964-4d54-11e8-9eba-ef41cd7ae828.png)

**Comment by dcmorse** [comment]
Yes, it's easy.
