### ISSUE TITLE
When figure note starts with comma, don't put a space before it.

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#361]
![comma](https://user-images.githubusercontent.com/10550086/39522860-3f11b12e-4dd9-11e8-80fb-5808f3a2e8c7.png)

**Comment by cranhandler** [comment]
Comma, period, semicolon.

NOT any non-alphanumeric character. N-dashes work as desired right now, as do * and + .

**Comment by dcmorse** [comment]
fixed in the murky depths of time
