### ISSUE TITLE
User Notification Settings

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#364]
Upon account creation (or edit account) 

Allow users to `opt in` to
- [ ] receive communications about new contradb features

and to `opt out` from 
- [x] receiving individual emails from Adminisaur in the event of dance curation.
-`opting out from dance curation notifications means that, in the event that a dance you enter is broken, it will be switched to private and you will not be contacted`

We will never share your address or ask for money. 

Taking care that this is compliant with our current language, or updating language to make it compliant.

**Comment by cranhandler** [comment]
Once this is accomplished, Adminisaur will email all users a one-time email letting them know about this new permissions power they have.

**Comment by dcmorse** [comment]
Use BCC on that, obviously. :)

**Comment by dcmorse** [comment]
If they've got the admin-feedback feature enabled, and if we're logged in as admins, we can put their mailto-able email address on every dance show page they own. It'll save you the trouble of looking up their email address.

Actually, we should show email address to admins on the user show page. Right now we don't.

**Comment by dcmorse** [comment]
Going forward, I would like to check both boxes by default. 
Old users would be grandfathered out of site news, unless they explicitly opt-in.

**Comment by dcmorse** [comment]
On further thought, I wanna go with radio buttons:

If there's a problem with one of my published dances:
- [ ] Mark it private.
- [x] Contact me, and only if there's no response: mark the dance private.

ContraDB is under heavy development.
- [x] Email me feature announcements.
- [ ] Don't bother me.

**Comment by dcmorse** [comment]
![screenshot-2018-5-9 contra](https://user-images.githubusercontent.com/10550086/39815542-df739252-535d-11e8-959a-5271ccec9668.png)

**Comment by cranhandler** [comment]
Note the final wording is better than what was proposed above, to wit: 
Existing users have their status set to 'unknown' until they log in to modify it. Emails went out to groups of users under User Agreement 0.0 and User Agreement 0.1 letting them know of the changes. 


Sign Up
Email
jane@gmail.com
Name
Jane Smith
Password
minimum 8 characters
Password Again

Public Data Handling
If an issue is noticed in a dance I published, moderators should...
(radio button) collaborative - edit or unpublish the dance, emailing me the original text
(radio button) owner - email me, then if I don't repsond within 2 weeks unpublish the dance
(radio button) hermit - unpublish the dance, don't contact me
Newsletter
(radio button) Email me about site upgrades
(radio button) No email

User Agreement
The purpose of ContraDB is to build a free, shared, high-quality, machine-readable database of contra dances, so that humans can dance and have fun. Having said that, bad things can happen on the internet - you assume the risk that your uploaded data could be lost, modified, or stolen.

Your email address will be used to send password reset links and email you asked for above. It will not be intentionally given to third parties, nor will we spam you with advertisements.
