### ISSUE TITLE
Dave dance entry todo

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#372]
- [x] Pieces of 8 - Peter Foster
- [ ] I wanna dance - Erik Hoffman

**Comment by cranhandler** [comment]
Erik Hoffman's website appears to be offline, and I can't find where I logged this dance in my email at all. 

But I did find it here

http://barndancecaller.net/dancecards/I%20wanna%20dance.html
I wanna dance
--

**Comment by dcmorse** [comment]
Help! I don't understand the B1. 
https://contradb.com/dances/913 [admin required, or see contradb slack #general]
