### ISSUE TITLE
Caps lock dialects

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#379]
when in the notes, Ladle did not dialectically translate to ladies. Consider finding a way that all capitalization schemes, including Title Case and YELLING CASE, will still translate.

**Comment by dcmorse** [comment]
also sentence capitalization case, e.g. "Right shoulder round is a move."

**Comment by dcmorse** [comment]
# First Pass:
Match terms case insensitively and keep the case they have in their stored substitution. 

# Super Advanced Rocket Science Version
compare the case they used to the case in their substitution, figure out if it's `Sentence cap case`, `Title Case`, `YELLING CASE`, `rAnSoM NoTe CaSe`, or whatever, and apply the same scheme to the stored db term. Then squirt out the db term again in the same case.
