### ISSUE TITLE
Contradb isn't yellow

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#386]
It is kind of pink usually?

Suggested alternate colors
http://www.colourlovers.com/color/FFF9D2/Countess_of_Tyrone
http://www.colourlovers.com/palette/4572614/Casa_de_Imilla
http://www.colourlovers.com/color/F3EF7D/Butter_Yellow
http://encycolorpedia.com/fbecd2
http://encycolorpedia.com/fff8dc

**Comment by dcmorse** [comment]
I tweaked the color as per your suggestions. LMK what you think.

**Comment by cranhandler** [comment]
The yellow looks nice, but now the beige is too pale. Eventually, let's go
to the blueberry corn pop scheme.
