### ISSUE TITLE
ocean wave center's hand radio button

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#387]
I want the 'centers take [right | left] radio button to be unselected until I click on it. Too often, since there's not a blank in the text, I carry on blithely assuming *I* had clicked 'left', which I didn't, because the dance actually called for right. Giving an unselected radio button would force me to think critically each time upon dance entry.

**Comment by dcmorse** [comment]
It appears this was resolved in 63211ee53c52b48ce6656eb4f56fc73b6f10505d
