### ISSUE TITLE
Update help page

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#389]
in between 'How do I search for dances?' and 'Can someone talk me through this?' , please insert

What is a gentlespoon?
     -- that's our default dialect. Don't like it? Change what you see [here](http://contradb.com/dialect).

**Comment by dcmorse** [comment]
I think it's a little weird to have link text use a pronoun like [this](contradb.com). I'm adjusting this copy a little. Currently using
```
        <dt>What is a gentlespoon?</dt> <dd>that's our default dialect. Don't like it? Log in and adjust it using the <%= link_to("dialect editor", dialect_path) %>.</dd>

```
