### ISSUE TITLE
Search/filter criterion for dance formation

### ISSUE THREAD

**Issue by djpohly** [contradb/contra#395]
![cool hip dancer](https://i.ytimg.com/vi/v7b3yzjAv8c/hqdefault.jpg?sqp=-oaymwEXCPYBEIoBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCoLe4I48OQ3PrecmLvU3Aa4wi2WA)

"I am a cont-ra dance caller, and I want to call a cont-ra dance, but my program has lots of Becket. Is there a non-Becket dance here?"

"Yes, I am a cont-ra dance database, and I have cont-ra dances which are not Becket."

"Okay cont-ra dance database, please show me cont-ra dances which are not Becket."

"No.  I do not want to show you cont-ra dances which are not Becket.  I want to show you every cont-ra dance and sort them by formation so you can page through them ten at a time."

"How about this. Please show me cont-ra dances which are improper."

"No.  I do not want to show you cont-ra dances which are improper.  I want to show you cont-ra dances which have the word 'improper' in the title, choreographer, or user."

"Wow.  Wowowow."

etc.

**Comment by cranhandler** [comment]
Touche!

**Comment by cranhandler** [comment]
+1 for this question 
Allison,

Would it be possible to add a filter by formation when searching? It would be very helpful.

Nicholas
