### ISSUE TITLE
Rory who?

### ISSUE THREAD

**Issue by djpohly** [contradb/contra#396]
ContraDB says "O'Moore."  One choreographer appears to have an unsurprising tendency toward "[O'Mohr](http://rickmohr.net/Contra/Dances.asp#MoverAndShaker)."  My own brain, upon first hearing it, decided "Rory Amore", a romantic misinterpretation to which I am still somewhat attached.

Nevertheless, Google search hits ([O'More](https://www.google.com/search?hl=en&q=%22rory%20o%27more%22)/[O'Moore](https://www.google.com/search?hl=en&q=%22rory%20o%27moore%22)) and [Ngrams](https://books.google.com/ngrams/graph?content=rory+o'more%2Crory+o'moore&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3) suggest that "O'More" is the most common spelling both currently and historically.

**Comment by jmdyck** [comment]
http://www.ibiblio.org/contradance/index/search.php?ti=rory finds 25 sources saying "O'More", none saying O'Moore".

(There is "Gay Rory O Moor" from Don Flaherty, which combines distinctive figures from "Gay Gordons" and "Rory O'More", but there's no explanation for the spelling.)

**Comment by cranhandler** [comment]
Thanks! New plan: 

Current figure Rory O'Moore will be renamed Rory O'More so the DB matches convention. 

All users wanting to call Rory Amore will find our [dialects tool](http://contradb.com/dialect) will do the trick :)
