### ISSUE TITLE
form long waves language

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#398]
needs to be 'ladles face in, gentlespoons face out', where who is facing IN is listed first in the text.

**Comment by cranhandler** [comment]
http://contradb.com/dances/420/

**Comment by dcmorse** [comment]
I've changed the language.

## Question:

![who](https://user-images.githubusercontent.com/10550086/40886844-e1688594-6704-11e8-88dc-8aa6fe8203e9.png)

The `who` select still chooses who *faces out*. Given that who faces in is always first, do you think I need to go through and invert all the stored values to list who faces in? It'll take ~20 minutes.

**Comment by dcmorse** [comment]
I went ahead and did it. It actually took 40 minutes. :)
