### ISSUE TITLE
smush to a wave

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#404]
http://contradb.com/dances/540 Sarah Kaiser's Evanesce
also a Seth Tepfer dance

**Comment by dcmorse** [comment]
Why isn't this "form an ocean wave and balance" in the A1? 0 beats to form the wave (it's just a step) 4 beats to balance it.

**Comment by dcmorse** [comment]
bump

**Comment by cranhandler** [comment]
Then how do I fill the 8 beats at the bottom of B2? 

The wave is formed (in my brain) BEFORE the first note of the A1, and it seems misleading to include the "pickup note" of B2 in at the top of the dance. I think a preamble is a better fit in these cases, because you read it once at the beginning of the walkthrough, and it's not present through the rest of your calls to confuse you.

**Comment by dcmorse** [comment]
I don't know what to say to you to convince you that this is the best way to encode the thing. I don't think dancers can tell the difference between a caller saying something effective at beat 63.9999 and something effective at beat 0. 

If you're having this much cognitive dissonance, maybe you could compromise by rotating the dance by 32 beats and posting it as a "variation". That's probably less bad than it's current 72 beat form.

**Comment by dcmorse** [comment]
Another alternative that I think is an improvement:

- Make an "instant" form ocean wave at the end of the b2.
- Use the freestanding "balance" figure on beat 0 of the dance.

**Comment by dcmorse** [comment]
I make a motion to close this issue, @cranhandler

**Comment by cranhandler** [comment]
Granted.

Pardon brevity; sent by smartphone.
