### ISSUE TITLE
Search 2.0

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#411]
While I'm really proud of the search functionality we've built - remember a year ago the contra dance community literally could not even imagine our advanced figure search? - it is no excuse to rest on our laurels. There are a bunch of search issues, and many of them are juicy, easy targets. I think they've the makings of a new project. And I'm going to create some other component issues for things I'd like to see. 

- advanced figure search duplicate figures #360
- new ways for searching for: figure1 [some stuff] figure2 #375
- no way to search for A then [some figures] then A again #303
- Time-masked search #307
- figure search 'then' returning bogus results #269
- search results show matched figures #409 (new)
- search pulldown: text #410 (new)
- Search/filter criterion for dance formation #395
- search tree manipulation - hug and raise #412 (new)
- Search for "balance" to do the right thing #416

**Comment by dcmorse** [comment]
This issue was not as good an idea as the [search](https://github.com/contradb/contra/labels/search) tag. Closing this in favor of that.

**Comment by cranhandler** [comment]
Then I am re-opening each of those individual issues, which were closed when you mentioned them in 411.
