### ISSUE TITLE
search tree manipulation - hug and raise

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#412]
## Scenario 1
It often happens that you're searching for something - say "partner meltdown swing for 16 beats", and then you realize you want to trim the search further - say "then no ladies chain". Having laboriously entered the search for "partner meltdown swing for 16 beats", the user currently has no option but to change that to "then", and then reenter "partner meltdown swing for 16 beats" as the first entry. 

## Story 1:  → hug
Dave would like for each search node to have a `→` button, to the left of the `...` button, that wraps the node in a "then" node. The user can then modify the "then" node to be an "and" node, an "or" node, or whatever they want. 

## Scenario 2
Sometimes you put in multi-node search terms, and then decide you only care about one of them. You'd like to elevate that subnode to the level of the node, discarding all the other subnodes
## Story 2: ← raise
Dave would like for each non-root search node to have a `←` button so he can elevate a subnode and delete all it's siblings without starting his query over from scratch.

Illustration will be forthcoming

**Comment by dcmorse** [comment]
![hug](https://user-images.githubusercontent.com/10550086/40923933-a6fa9000-67db-11e8-8af9-dfab31173b29.png)

**Comment by cranhandler** [comment]
I like this, it helps with https://github.com/contradb/contra/issues/415

**Comment by dcmorse** [comment]
namestorming: _envelop_ and _extract_

**Comment by dcmorse** [comment]
Blocked for new search editor.

**Comment by dcmorse** [comment]
We're going to use the more-familiar cut-copy-paste paradigm, along with the current casting behavior
