### ISSUE TITLE
long waves first & second corners

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#442]
Long waves needs first and second corners to be the face in it face out options
http://contradb.com/dances/622

**Comment by dcmorse** [comment]
I don't know what the deal is. First and second corners were already in the menu right under ones and twos. Maybe he reported the wrong figure?

**Comment by dcmorse** [comment]
No, even with the example dance, it's _right there_. I think it's an accident. 

![huh](https://user-images.githubusercontent.com/10550086/42425087-29f8a8b8-82dd-11e8-98bc-05288198f97f.png)

**Comment by cranhandler** [comment]
I have updated this dance, but in the future please don't close the issue til the dance, as well as the issue, has been fixed.
