### ISSUE TITLE
dance count counts private dances

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#445]
It confused Cis Hinkle. Just change it to count another way, maybe: X public, Y private-but-visible

**Comment by chetgray** [comment]
I can take a look at this!

Should count of private dances even be public?

**Comment by cranhandler** [comment]
Got another report of this "bug". ---I'll admit I thought it was desired behavior, and I apparently am wrong.  I'm happy to put this in 'to do', @chetgray if you want to jump in you're more than welcome to! 

>The number of dances by a choreographer  is not decremented when necessary.  Eleven dances are attributed to me in the choreographer table, while only 6 such dances exist.  Seems that deleted versions of dances are still  being counted

**Comment by dcmorse** [comment]
There's a rails concept of a 'scope' that narrows the db query. Using these in the choreographer controller would alter the behavior to the way that people expect. This project is super-easy for me, so I wouldn't recommend anyone else do it.
