### ISSUE TITLE
Search not finding dance that fits

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#461]
The following search should return You Can't Get There From Here, but doesn't.

We don't understand why!

#figure-query-buffer :

"["then",["or",["figure","form an ocean wave","true","*","*","*","*","*","*"],["figure","form long waves"]],["or",["figure","allemande"],["then",["figure","balance"],["figure","allemande"]]]]"

**Comment by dcmorse** [comment]
I mean, I think it's because the inner `(then balance allemande)` selects the index of the allemande, which is not one higher than index of the first clause of the outer then. Kinda a deep problem in the way searches are evaluated, I think.
