### ISSUE TITLE
mad robin with nil beats causes loss of dance edits

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#473]
1. make 50,000 changes to a dance
2. add a mad robin
3. neglect to set the number of beats 
4. save dance
:bomb: :face_with_head_bandage: 

## Possible quick fixes:
1. set beats to 8 by default
2. set beats to 6 by default

**Comment by cranhandler** [comment]
This should be set to 6 by default.

**Comment by dcmorse** [comment]
Agreed. 6 forces people to think. 8 allows them to make sloppy errors because they don't have to think.
