### ISSUE TITLE
remove 'progress' figures from all dances

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#474]
Once pilcrow goes live, the first data task is to edit dances and remove the progression figure. It's only left in about 20 (see slack). 

Blocked for pilcrow deploy.

**Comment by dcmorse** [comment]
Unbloxked because pilcrows are live.

**Comment by cranhandler** [comment]
Also Stargazer https://contradb.com/dances/151

**Comment by cranhandler** [comment]
All 'progress' figures except those two are now handled.

When we have a solution for them, https://contradb.com/dances/566 will be well-served by that solution as well.

**Comment by dcmorse** [comment]
Can you write Chet and get him to accept my rewrites? If so, I can unblock and remove the progress figure.

**Comment by dcmorse** [comment]
We've been held up on deleting the 'progress' figure for months, due to inaction on these dances. They both have better versions by user #2. I think it's time to do something.

**Comment by dcmorse** [comment]
I'm going to write a migration that converts remaining `progress` figures to customs. 
I need to finish something.

**Comment by dcmorse** [comment]
resolved by #536
