### ISSUE TITLE
Slide left language

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#476]
Once pilcrow is fully implemented, 'slide left along the set' won't need the 'to new neighbors' descriptor.

![image](https://user-images.githubusercontent.com/16180173/43672098-2f77bd26-976c-11e8-92fd-eedb0e54bf1c.png)

**Comment by cranhandler** [comment]
Wait, wait, please undo! Right now I am using this language for forensic purposes, to see where to put the pilcrows!

**Comment by dcmorse** [comment]
Oh, the secret formula was this:
*It appeared on every single slide left figure*!!!
So if you see a slide left, you know it said "to new neighbors". 

It wasn't the smartest knife in the drawer!

**Comment by cranhandler** [comment]
Please? It isn't hurting users, it will be gone before the end of the week, and it was helping me. It was like having a little cellophane flag on the toothpick in your sandwich, so you don't overlook the toothpick and hurt your mouth.
