### ISSUE TITLE
Dynamic Heys

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#480]
We need to create and act on a hey plan. 

Reading these parameters, maybe we need to handle this the way we handle pull by (`pull by direction` is a figure, `pull by dancers` is another figure) . `hey` is a figure supporting "classic" full and half heys. `hey until` is more complex, with dancer and place support. 

Proposal: 

figure: hey 
radio button: [half | full ]
lead: [gentlespoons | ladles | partners | first corners | ... ] 
passing: [left | right]
ricochet: [checkbox]
who_ricochets: [pairz]
which_pass: [null | first pass | second pass]

figure: hey until
lead: [gentlespoons | ladles | partners | first corners | ... ] 
passing: [left | right]
until: [pairz]
until_meet: [partner | neighbor | next ladle | ...] also possible [gentlespoon's home side | long wavy lines ] 

Language for a plain-jane hey figure to read

half hey - ladles start passing left shoulders
or
half hey - partners start passing right shoulders
or
full hey - ladles start passing right, gentlespoons push back on second pass

language for a hey-until to read

hey - ladles lead passing left until you meet your neighbor

Possible issues to source from:
 https://github.com/contradb/contra/issues/341
https://github.com/contradb/contra/issues/290
https://github.com/contradb/contra/issues/122

**Comment by cranhandler** [comment]
Not yet actionable: ricochet hey doesn't support multiple ricochets.

**Comment by dcmorse** [comment]
Let's talk about ricochets. For a simple half hey, either the gentlespoons or the ladles could ricochet. There could be a checkbox for each, as they're independent. For a simple full hey, either the gentlespoons or the the ladles could ricochet on the first pass, then either the gentlespoons or the ladles could ricochet on the second pass. For example, I think there's a CR dance with ladies leading then gents ricocheting on the first pass, and ladies ricocheting on the second pass. Lastly, not all heys have one role going first and the second role going second. It's possible to have a hey where the ones lead, in which case the ricochet checkboxes would need to be labeled with 'ones first pass', 'twos first pass', 'ones second pass', 'twos second pass'. Hm.

**Comment by dcmorse** [comment]
Desire the ability to start and end heys in ocean waves.

**Comment by cranhandler** [comment]
Make sure heys support first and second corners

**Comment by dcmorse** [comment]
So the hey editor idea we have is this, I think:

Who: [pair options] (for the sake of the below, suppose it's 'ladles')
Start: 'pass right in the center, left on the ends', 'pass left in the center, right on the ends', 'pass left on the ends, right in the center', 'pass right on the ends, left in the center'
End When: [_] half hey [_] full hey [_] ladles pass right shoulders first time [_] pass left on the ends first time [_] gentlespoons pass right shoulders first time [_] half a hey [More to be written here] (note that radio labels change based on the 'who' and the Start, and are Maybe Very Hard)
Ricochets: [_] first ladle [_] first gent [_] second ladle [_] second gent (note that radio labels change based on the 'who' and ideally disappear for shorter heys - these are Maybe Very Hard!)

**Comment by dcmorse** [comment]
Implemented in #502
