### ISSUE TITLE
dolphin hey

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#487]
We don't currently support Dolphin Hey, as used in 

https://contradb.com/dances/568
https://contradb.com/dances/408
https://contradb.com/dances/422

dolphin hey - #1 raven leading right shoulder around #2 lark, finishing on home side with partner
dolphin hey, ones passing right shoulders with 2nd raven to begin +
dolphin hey (lark one pass raven two by the left)

Looks like parameters should be

dolphin hey 
beats default to [8]
who starts [ladle 1, gentlespoon 1, ladle 2, gentlespoon 2]
by the [right, left] (defaults to unselected) 
around whom [gentlespoon 2, ladle 2, gentlespoon 1, raven 1]

When done, alert user 47.

**Comment by dcmorse** [comment]
I'm having difficulties. Am I already supposed to understand what happens in a dolphin hey to be able to understand this post, or am I supposed to be able to look at this post and understand a dolphin hey?

**Comment by cranhandler** [comment]
Looking at this post will allow you to write a figure for dolphin hey so
people can enter their dances, Chinese room style.

To understand a dolphin hey, see Bob's videos on these dances in the
Childgrove archive, and/or ask Bob to walk you through one.

Pardon brevity; sent by smartphone.

**Comment by cranhandler** [comment]
Wording should be: 
dolphin hey - ladle leads by right around gentlespoon two

**Comment by dcmorse** [comment]
Blocked because I can't find a breakdown or video of dolphin hey choreography, and from the words alone I don't understand how it's different from a slow-motion do si do. I'm scared to proceed with this little 'big picture'.

**Comment by cranhandler** [comment]
https://www.youtube.com/watch?v=g-8LyExynvA

this one is smooth. 

There's also both a video accompanied by text here http://dancevideos.childgrove.org/ecd/ecd-modern/511-saphire-sea

Let me know if these help?

**Comment by dcmorse** [comment]
Helps a lot, thank you!

I note the design decision to have the 'around whom' be a single dancer and not a couple. Are you suuuuuure with that? Wouldn't it be more evocative to have it name a couple first? All three writeups of Sapphire Sea are that way.

**Comment by cranhandler** [comment]
Write it as that (per transcription)

Pardon brevity; sent by smartphone.

**Comment by dcmorse** [comment]
What? Around-whom is a couple or a dancer?

**Comment by dcmorse** [comment]
So I'm seeing several alternatives. What are your feelings?


## what you wrote in the first post - underspecified?
who starts [ladle 1, gentlespoon 1, ladle 2, gentlespoon 2]
by the [right, left] (defaults to unselected)
around whom [gentlespoon 2, ladle 2, gentlespoon 1, raven 1]
beats default to [8]

## three individuals, overspecified?
who starts [dancer1]
by the [right, left] (defaults to unselected)
around whom [dancer2]
with [dancer3]
beats default to [8]

## pair-centric, overspecified?
who starts [pair]
led by [dancer1]
around whom [dancer2]
by the [right, left] (defaults to unselected)
beats default to [8]

## pair-centric, underspecified?
## pair-centric
who starts [pair]
(leader is implicit since they have to go towards...)
around whom [dancer2]
by the [right, left] (defaults to unselected)
beats default to [8]

**Comment by rwiener** [comment]
I don't think the original is underspecified, it give me everything I need to know. Beats should default to 16, not 8. In my current dances, I use the following notation:  
"Dolphin hey, Lark1 leads passing Raven2 by the left." 
I realize that there's a hidden assumption that the move is with current neighbors, but that is the case for many other moves. We don't notate "with current Ns, R&L Thru." We just say notate "R&L Thru."

**Comment by dcmorse** [comment]
Okay let's go with the original spec, naming 2 individual dancers. Removing [blocked] tag.

**Comment by dcmorse** [comment]
I think we wanna change either the subject or the object to be a pair, because that way it's *much easier* to determine at a glance who the pair is. If we say `first ladle dolphin hey second gentlepsoon by the right`, it's not immidately obvious which of those two is part of a convoy of two dancers. But if we say either `first ladle dolphin hey twos by the right` or `twos dolphin hey first ladle by the right`, it's pretty clear, eh?

**Comment by cranhandler** [comment]
"first ladle dolphin hey twos by right" doesn't tell me which two the first
ladle starts with. I would prefer to have "first ladle dolphin hey second
gentlespooon by the right" .   Personally I think 'which who-pair dolphin
heys which whom-pair* is obvious from context, while starting with
ladlewhom or gentlespoonwhom is not obvious unless stated explicitly.

Maybe, like the way you format "star - wrist grip"
you could write

"ones dolphin hey - first ladle passing second gentlespoon by right" ?

This is still clunky, but at least doesn't remove information I rely on.

**Comment by dcmorse** [comment]
> "ones dolphin hey - first ladle passing second gentlespoon by right" ?
> 
> This is still clunky, but at least doesn't remove information I rely on.

Aye, clunky but unambiguous. I think the word-glue could be better. Maybe "ones dolphin hey - first ladle lead past second gentlespoon by the right". 

If we could count on the context to have an arrangement for the center two dancers, then this would be good enough. This *is good enough* for our three existing examples, but might not be the case coming out of, say, a ones-swing-in-the-center.
![cdb](https://user-images.githubusercontent.com/10550086/44295624-8409b400-a272-11e8-9a4c-039510703626.png)

Word-glue subject to debate, I'm more interested in the parameters boxes now.

**Comment by rwiener** [comment]
Beats appear to still default to 8, but should be 16.

**Comment by cranhandler** [comment]
User feedback:


> Hi user, I noticed https://contradb.com/dances/422 had a dolphin hey added as a custom (probably from before we supported the figure). I went in and codified it so it shows up in search, but I'm not 100% that it has fidelity. I copied your original custom text into notes so anyone can infer. But would you be willing to see if the figure's language matches your intent? If not, I'm happy to hear how it should be instead.
> 
> Thanks, adminisaur




> Oh, excellent! I changed the 'who' from 'ravens' to 'ones'. It might be good to allow a bit more detail there, since it's specifically the #1 raven starting the hey, followed closely by their partner, but at least for my dance it should be reasonably evident based on where the previous figure puts everyone.

**Comment by dcmorse** [comment]
I make a motion to close.

**Comment by cranhandler** [comment]
Fine to close, we can re-open if we get additional requests.
