### ISSUE TITLE
chirality of chain

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#488]
Proposal: give "chain" a radio button for
hand: [right | left], default to right.

Idea: this could be implemented in dialects similar to %s gyre: default language would be 
'chain' for right chain and 'left hand chain' for left chain

but someone whose dialect was '%s hand chain' could see
'right hand chain' and 'left hand chain'

**Comment by cranhandler** [comment]
Update. 

Current implementation plan:
Proposal: give "chain" a radio button for
hand: [right | left].

Default for a chain by ladles is right. Default for a chain by gentlespoons is left. Display the word for this when it's the unexpected variant 

words:
ladles chain
ladles left-hand chain
gentlespoons chain
gentlespoons right-hand chain

%s hand chain will be spun off to another issue.

**Comment by dcmorse** [comment]
We consistently use "left hand" and "right hand" and not "left-hand" and "right-hand", so I'm not hyphenating those words.

**Comment by cranhandler** [comment]
"By the right hand" or "take right hands"is not the same as "right-hand
chain".

Are there other cases where we're using it as an adjective and not
hyphenating today?

Pardon brevity; sent by smartphone.

**Comment by dcmorse** [comment]
It seems analogous to the use in pull-by, for example:

![hands](https://user-images.githubusercontent.com/10550086/44128719-0d674b74-a00a-11e8-99d8-bf1b2fee677c.png)

Also maybe revolving door.

**Comment by cranhandler** [comment]
I don't see those as analogues, isn't pull-by usually "pull by the
(adj)right (n)hand on the left diagonal"

Like, if left is the adjective and hand is the noun, these should not be
hyphenated.

If left and hand are both the adjective and something else is the noun,
then the hyphen is needed. (Adj)left-hand (n)chain.

The only analogue I can think of that we might have as a predecessor is
right-hand star, did we hyphenate that?

Pardon brevity; sent by smartphone.

**Comment by dcmorse** [comment]
That doesn't apply because it's 'star right' and not 'right hand star'. Whatever you want to do is ok.

**Comment by cranhandler** [comment]
Let's please hyphenate until such point as we receive feedback.
