### ISSUE TITLE
Searching Progressions

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#490]
We'd like to search progressions 

for sure:
-is it double or single or no progression?
-which figure has the progression? 

possibly:
-who are you with when you progress (shadow or partner?)
-what is the figure after the progression?
-is the progression in the A1, A2, B1, or B2
-is the progression at the top of the phrase? bottom of the phrase? or neither?

**Comment by dcmorse** [comment]
> - is it double or single or no progression?

Nothing for double yet, that's #360 

> - which figure has the progression?

done! Thanks to our good buddy `&` the search operator. 

> - who are you with when you progress (shadow or partner?)

huh. No good ideas on this on my end. 

> - what is the figure after the progression?

done! thanks to our good buddy `then` the search operator. 

> - is the progression in the A1, A2, B1, or B2
> - is the progression at the top of the phrase? bottom of the phrase? or neither?

not done! Kinda do-able with `&` and some filters that I think are named in another (unprioritized) issue.
