### ISSUE TITLE
heys 2nd pass

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#516]
== 20180924041545 Hey2ndPass: migrating =======================================
- [ ] Ad Soe [Serving REELness](http://contradb.com/dances/673) http://contradb.com/dances/673   
- [x] Alo Jnak [A Proper Potpourri](http://contradb.com/dances/384) http://contradb.com/dances/384  collaborative *private*
- [x] Alo Jnak [A Proper Trifle](http://contradb.com/dances/399) http://contradb.com/dances/399  collaborative 
- [x] Alo Jnak [A. O. 's No-No Software Testing](http://contradb.com/dances/350) http://contradb.com/dances/350  collaborative *private*
- [x] Alo Jnak [Apples and Concord Grapes](http://contradb.com/dances/102) http://contradb.com/dances/102  collaborative 
- [x] Alo Jnak [Are You 'Most Done](http://contradb.com/dances/197) http://contradb.com/dances/197  collaborative 
- [x] Alo Jnak [Azure Aster](http://contradb.com/dances/316) http://contradb.com/dances/316  collaborative 
- [x] Alo Jnak [Bee in her Bonnet](http://contradb.com/dances/99) http://contradb.com/dances/99  collaborative 
- [x] Alo Jnak [Butterfly Kiss](http://contradb.com/dances/694) http://contradb.com/dances/694  collaborative *private*
- [x] Alo Jnak [Carrot Cake and Candles](http://contradb.com/dances/222) http://contradb.com/dances/222  collaborative 
- [x] Alo Jnak [Corn Pops and Blueberries 0.0](http://contradb.com/dances/657) http://contradb.com/dances/657  collaborative *private*
- [x] Alo Jnak [Cosmos](http://contradb.com/dances/315) http://contradb.com/dances/315  collaborative 
- [x] Alo Jnak [Dancing Through the Decades](http://contradb.com/dances/221) http://contradb.com/dances/221  collaborative 
- [x] Alo Jnak [Delphiniums and Daisies](http://contradb.com/dances/354) http://contradb.com/dances/354  collaborative 
- [x] Alo Jnak [Diamond Allotrope](http://contradb.com/dances/631) http://contradb.com/dances/631  collaborative 
- [x] Alo Jnak [Dr. Whiting's Delight](http://contradb.com/dances/328) http://contradb.com/dances/328  collaborative 
- [x] Alo Jnak [Easily Led Lad](http://contradb.com/dances/155) http://contradb.com/dances/155  collaborative 
- [x] Alo Jnak [Fairport Harbor Hey B2](http://contradb.com/dances/504) http://contradb.com/dances/504  collaborative 
- [x] Alo Jnak [Fat Bear's Reel](http://contradb.com/dances/356) http://contradb.com/dances/356  collaborative 
- [x] Alo Jnak [Fly Around My Pretty Little Miss](http://contradb.com/dances/90) http://contradb.com/dances/90  collaborative 
- [x] Alo Jnak [Fun Dance For Linda (for Linda Leslie) for Linda Leslie ](http://contradb.com/dances/551) http://contradb.com/dances/551  collaborative 
- [x] Alo Jnak [Heart of Glass](http://contradb.com/dances/382) http://contradb.com/dances/382  collaborative 
- [x] Alo Jnak [Hope's Spirit](http://contradb.com/dances/607) http://contradb.com/dances/607  collaborative 
- [x] Alo Jnak [Into the DMZ](http://contradb.com/dances/317) http://contradb.com/dances/317  collaborative 
- [x] Alo Jnak [Joyride](http://contradb.com/dances/256) http://contradb.com/dances/256  collaborative 
- [x] Alo Jnak [Jurassic Redheads](http://contradb.com/dances/495) http://contradb.com/dances/495  collaborative 
- [x] Alo Jnak [Laura's 3/4 Century](http://contradb.com/dances/227) http://contradb.com/dances/227  collaborative 
- [x] Alo Jnak [Leap Dance](http://contradb.com/dances/101) http://contradb.com/dances/101  collaborative 
- [x] Alo Jnak [Linda's Surprise (for Linda Leslie) for Linda Leslie ](http://contradb.com/dances/550) http://contradb.com/dances/550  collaborative 
- [ ] Alo Jnak [Lunt Birthday Waltz](http://contradb.com/dances/216) http://contradb.com/dances/216  collaborative 
- [x] Alo Jnak [Mad About You](http://contradb.com/dances/163) http://contradb.com/dances/163  collaborative 
- [x] Alo Jnak [Missing Duck simple A variation](http://contradb.com/dances/690) http://contradb.com/dances/690  collaborative 
- [x] Alo Jnak [Missing Duck](http://contradb.com/dances/689) http://contradb.com/dances/689  collaborative 
- [x] Alo Jnak [Not Quite Fifty Software Testing](http://contradb.com/dances/348) http://contradb.com/dances/348  collaborative *private*
- [x] Alo Jnak [Phinney Gaffer Becket](http://contradb.com/dances/470) http://contradb.com/dances/470  collaborative *private*
- [x] Alo Jnak [Princeton Petronellas](http://contradb.com/dances/320) http://contradb.com/dances/320  collaborative *private*
- [ ] Alo Jnak [Rad Robin](http://contradb.com/dances/228) http://contradb.com/dances/228  collaborative 
- [x] Alo Jnak [Ramsay Chase](http://contradb.com/dances/661) http://contradb.com/dances/661  collaborative *private*
- [x] Alo Jnak [Shift Happens](http://contradb.com/dances/245) http://contradb.com/dances/245  collaborative 
- [x] Alo Jnak [Snakes](http://contradb.com/dances/692) http://contradb.com/dances/692  collaborative 
- [x] Alo Jnak [String of Swings](http://contradb.com/dances/543) http://contradb.com/dances/543  collaborative 
- [x] Alo Jnak [Sweet Potatoes](http://contradb.com/dances/496) http://contradb.com/dances/496  collaborative 
- [x] Alo Jnak [The Carousel](http://contradb.com/dances/650) http://contradb.com/dances/650  collaborative *private*
- [x] Alo Jnak [The Contra Matrix Resolution](http://contradb.com/dances/468) http://contradb.com/dances/468  collaborative 
- [x] Alo Jnak [Three Sisters](http://contradb.com/dances/691) http://contradb.com/dances/691  collaborative 
- [x] Alo Jnak [Triassic Poetry](http://contradb.com/dances/373) http://contradb.com/dances/373  collaborative 
- [x] Alo Jnak [Truffles for Breakfast](http://contradb.com/dances/86) http://contradb.com/dances/86  collaborative 
- [x] Alo Jnak [Twirling At The Altar](http://contradb.com/dances/494) http://contradb.com/dances/494  collaborative 
- [x] Alo Jnak [Weave Me the Sunshine](http://contradb.com/dances/226) http://contradb.com/dances/226  collaborative 
- [x] Alo Jnak [You and I ](http://contradb.com/dances/164) http://contradb.com/dances/164  collaborative 
- [x] Ben Wrer [The Erik Effect](http://contradb.com/dances/570) http://contradb.com/dances/570  owner 
- [x] Bin Rnat [Five Long Years](http://contradb.com/dances/385) http://contradb.com/dances/385   
- [x] Ce Ga [Rollin' Outta Barstow](http://contradb.com/dances/267) http://contradb.com/dances/267  owner *private*
- [x] Ce Ga [Spring Break (variation) variation ](http://contradb.com/dances/243) http://contradb.com/dances/243  owner 
- [x] Ce Ga [The Wise People of Chicago](http://contradb.com/dances/129) http://contradb.com/dances/129  owner 
- [x] Ce Ga [[untitled], variation](http://contradb.com/dances/29) http://contradb.com/dances/29   *private*
- [x] Ce Ga [[untitled]](http://contradb.com/dances/135) http://contradb.com/dances/135  owner *private*
- [x] Ce Ga [[untitled]](http://contradb.com/dances/34) http://contradb.com/dances/34   *private*
- [x] Cr Rvtz [Across Nottingham A](http://contradb.com/dances/218) http://contradb.com/dances/218   
- [x] Cr Rvtz [Across Nottingham B](http://contradb.com/dances/219) http://contradb.com/dances/219   
- [x] Cr Rvtz [Dar Trek variation](http://contradb.com/dances/205) http://contradb.com/dances/205   
- [x] Cr Rvtz [Dar Trek](http://contradb.com/dances/202) http://contradb.com/dances/202   
- [x] Cr Rvtz [Southern Summer](http://contradb.com/dances/512) http://contradb.com/dances/512   
- [x] Dn Wlna [32 Seconds](http://contradb.com/dances/491) http://contradb.com/dances/491  collaborative 
- [x] Dn Wlna [Chain, Chain, Roll Away](http://contradb.com/dances/513) http://contradb.com/dances/513  collaborative 
- [x] Dn Wlna [Return to Sender](http://contradb.com/dances/545) http://contradb.com/dances/545  collaborative 
- [x] Dn Wlna [The Birds and the Fleas](http://contradb.com/dances/406) http://contradb.com/dances/406  collaborative 
- [x] Dn Wlna [The Winter Storm](http://contradb.com/dances/473) http://contradb.com/dances/473  collaborative 
- [x] Dn Wlna [You Are On the Fastest Route](http://contradb.com/dances/518) http://contradb.com/dances/518  collaborative *private*
- [x] Dv Mre [ 40 Years of Penguin Pam refactored](http://contradb.com/dances/76) http://contradb.com/dances/76  collaborative *private*
- [x] Dv Mre [Across Nottingham A](http://contradb.com/dances/68) http://contradb.com/dances/68  collaborative *private*
- [x] Dv Mre [Autumn Air](http://contradb.com/dances/80) http://contradb.com/dances/80  collaborative 
- [x] Dv Mre [Butter](http://contradb.com/dances/94) http://contradb.com/dances/94  collaborative 
- [x] Dv Mre [Call Me](http://contradb.com/dances/43) http://contradb.com/dances/43  collaborative 
- [x] Dv Mre [Carousel](http://contradb.com/dances/653) http://contradb.com/dances/653  collaborative 
- [x] Dv Mre [Centrifugal Hey - software testing variation](http://contradb.com/dances/360) http://contradb.com/dances/360  collaborative 
- [x] Dv Mre [Dar Trek (alt. presentation) alt. presentation ](http://contradb.com/dances/311) http://contradb.com/dances/311  collaborative 
- [x] Dv Mre [E.J.M.J.F. in Cincinnati variation](http://contradb.com/dances/654) http://contradb.com/dances/654  collaborative *private*
- [x] Dv Mre [Hay in the Barn](http://contradb.com/dances/24) http://contradb.com/dances/24  collaborative 
- [x] Dv Mre [Ladleooper v0.1](http://contradb.com/dances/72) http://contradb.com/dances/72  collaborative *private*
- [x] Dv Mre [Mood Ring](http://contradb.com/dances/58) http://contradb.com/dances/58  collaborative *private*
- [x] Dv Mre [Parmesan](http://contradb.com/dances/314) http://contradb.com/dances/314  collaborative 
- [x] Dv Mre [Reddie to Roll](http://contradb.com/dances/477) http://contradb.com/dances/477  collaborative 
- [x] Dv Mre [Summer Sun](http://contradb.com/dances/11) http://contradb.com/dances/11  collaborative 
- [x] Dv Mre [Whitecaps](http://contradb.com/dances/609) http://contradb.com/dances/609  collaborative 
- [x] Dvn J. Phy [Daffy's Becket](http://contradb.com/dances/593) http://contradb.com/dances/593  owner *private*
- [x] Dvn J. Phy [Diana's Delight](http://contradb.com/dances/587) http://contradb.com/dances/587  owner 
- [x] Dvn J. Phy [Greentown Give and Take](http://contradb.com/dances/585) http://contradb.com/dances/585  owner *private*
- [x] Dvn J. Phy [Jubilation](http://contradb.com/dances/595) http://contradb.com/dances/595  owner 
- [x] Dvn J. Phy [Nothing Works and We Don't Know Why](http://contradb.com/dances/171) http://contradb.com/dances/171  owner 
- [x] Dvn J. Phy [Rant and Roar](http://contradb.com/dances/592) http://contradb.com/dances/592  owner 
- [x] Dvn J. Phy [Rory S'More (variation) variation ](http://contradb.com/dances/588) http://contradb.com/dances/588  owner 
- [x] Dvn J. Phy [Rory S'More](http://contradb.com/dances/589) http://contradb.com/dances/589  owner 
- [x] Dvn J. Phy [Silver Anniversary Reel](http://contradb.com/dances/574) http://contradb.com/dances/574  owner 
- [x] Dvn J. Phy [Step In Time](http://contradb.com/dances/591) http://contradb.com/dances/591  owner 
- [x] Dvn J. Phy [The Eyes Have It](http://contradb.com/dances/584) http://contradb.com/dances/584  owner *private*
- [x] Dvn J. Phy [Unknown](http://contradb.com/dances/586) http://contradb.com/dances/586  owner *private*
- [ ] Iac Bner [Another Jig Will Do](http://contradb.com/dances/530) http://contradb.com/dances/530  owner 
- [x] Iac Bner [Boulder Bound](http://contradb.com/dances/403) http://contradb.com/dances/403  owner 
- [x] Iac Bner [Grab Bag](http://contradb.com/dances/331) http://contradb.com/dances/331  owner 
- [x] Iac Bner [Hocus Pocus](http://contradb.com/dances/410) http://contradb.com/dances/410  owner 
- [x] Iac Bner [Jubilation (var) var ](http://contradb.com/dances/549) http://contradb.com/dances/549  owner 
- [x] Iac Bner [Last Hey](http://contradb.com/dances/387) http://contradb.com/dances/387  owner 
- [x] Iac Bner [Not My Second Rodeo](http://contradb.com/dances/413) http://contradb.com/dances/413  owner 
- [x] Iac Bner [Salmon and Halibut](http://contradb.com/dances/332) http://contradb.com/dances/332  owner 
- [x] Iac Bner [Splendid Starlings](http://contradb.com/dances/335) http://contradb.com/dances/335  owner 
- [x] Iac Bner [The Art of Negotiation](http://contradb.com/dances/425) http://contradb.com/dances/425  owner 
- [x] Iac Bner [They Stayed Here When They Disappeared](http://contradb.com/dances/463) http://contradb.com/dances/463  owner 
- [x] Iac Bner [Tom's Queue-less Carousel](http://contradb.com/dances/409) http://contradb.com/dances/409  owner 
- [x] Iac Bner [Trip To My Sunshine](http://contradb.com/dances/637) http://contradb.com/dances/637  owner 
- [x] Iac Bner [Trip to Mountain City](http://contradb.com/dances/686) http://contradb.com/dances/686  owner 
- [x] Iac Bner [Two Waves, Two Ways](http://contradb.com/dances/388) http://contradb.com/dances/388  owner 
- [x] Iac Bner [Unnamed Becket](http://contradb.com/dances/700) http://contradb.com/dances/700  owner 
- [x] Iac Bner [Weeks on the Road (var) var ](http://contradb.com/dances/334) http://contradb.com/dances/334  owner 
- [x] Iac Bner [Winter Fog](http://contradb.com/dances/415) http://contradb.com/dances/415  owner 
- [x] Kr Snmn [20 Below](http://contradb.com/dances/186) http://contradb.com/dances/186   
- [x] Kr Snmn [28th of Januray](http://contradb.com/dances/521) http://contradb.com/dances/521   
- [x] Kr Snmn [Butterfly Kiss](http://contradb.com/dances/209) http://contradb.com/dances/209   *private*
- [x] Kr Snmn [Dean's Valentine](http://contradb.com/dances/339) http://contradb.com/dances/339   *private*
- [x] Kr Snmn [Flirt Hurt](http://contradb.com/dances/182) http://contradb.com/dances/182   
- [x] Kr Snmn [Hallie's Comment](http://contradb.com/dances/183) http://contradb.com/dances/183   
- [x] Kr Snmn [Hey in the Barn](http://contradb.com/dances/266) http://contradb.com/dances/266   
- [x] Kr Snmn [Nomad's Land](http://contradb.com/dances/187) http://contradb.com/dances/187   
- [x] Kr Snmn [Whirl-A-Way](http://contradb.com/dances/235) http://contradb.com/dances/235   
- [ ] Ls Sers [Mood Ring](http://contradb.com/dances/56) http://contradb.com/dances/56   
- [x] Mce Fest [A.O.'s No-No ](http://contradb.com/dances/431) http://contradb.com/dances/431   
- [x] Mce Fest [Not Quite Fifty ](http://contradb.com/dances/435) http://contradb.com/dances/435   
- [x] Mce Fest [Where's Alex? ](http://contradb.com/dances/224) http://contradb.com/dances/224   
- [x] Mce Pag [Rusty Frame](http://contradb.com/dances/541) http://contradb.com/dances/541  owner 
- [x] Mi McCrc [Barack Me, Obamadeus](http://contradb.com/dances/480) http://contradb.com/dances/480  owner 
- [x] Mi McCrc [Neighbor, Neighbor On the Wall](http://contradb.com/dances/483) http://contradb.com/dances/483  owner 
- [x] Mi McCrc [Treasure of the Soda Bar](http://contradb.com/dances/486) http://contradb.com/dances/486  owner 
- [x] Ncla Sot [A Slice of Pinewoods](http://contradb.com/dances/274) http://contradb.com/dances/274  collaborative *private*
- [x] Ncla Sot [Amherst & Wooster](http://contradb.com/dances/305) http://contradb.com/dances/305  collaborative *private*
- [x] Ncla Sot [Delphiniums and Daisies](http://contradb.com/dances/293) http://contradb.com/dances/293  collaborative *private*
- [x] Ncla Sot [E6 contra dance](http://contradb.com/dances/296) http://contradb.com/dances/296  collaborative *private*
- [x] Ncla Sot [Happy Ending](http://contradb.com/dances/306) http://contradb.com/dances/306  collaborative *private*
- [x] Ncla Sot [Have I Danced This Before?](http://contradb.com/dances/299) http://contradb.com/dances/299  collaborative *private*
- [x] Ncla Sot [Leave Them Hanging](http://contradb.com/dances/290) http://contradb.com/dances/290  collaborative *private*
- [x] Ncla Sot [No Surprises](http://contradb.com/dances/277) http://contradb.com/dances/277  collaborative *private*
- [x] Ncla Sot [Rant and Roar](http://contradb.com/dances/270) http://contradb.com/dances/270  collaborative *private*
- [x] Ncla Sot [Southern Swing](http://contradb.com/dances/281) http://contradb.com/dances/281  collaborative *private*
- [x] Ncla Sot [Wave Mechanics](http://contradb.com/dances/284) http://contradb.com/dances/284  collaborative *private*
- [x] Ncla Sot [Welcome to DE DMV](http://contradb.com/dances/298) http://contradb.com/dances/298  collaborative *private*
- [x] Ncls Rctoh [Gotta Catch 'Em All](http://contradb.com/dances/617) http://contradb.com/dances/617   
- [x] Ncls Rctoh [Projectile Possums Variant](http://contradb.com/dances/623) http://contradb.com/dances/623   
- [x] Ncls Rctoh [Projectile Possums](http://contradb.com/dances/612) http://contradb.com/dances/612   
- [x] Rbn Bnj [A Last Hurrah](http://contradb.com/dances/459) http://contradb.com/dances/459  collaborative 
- [x] Rbn Bnj [Becketize the Baby](http://contradb.com/dances/439) http://contradb.com/dances/439  collaborative 
- [x] Rbn Bnj [Hay In the Barn](http://contradb.com/dances/454) http://contradb.com/dances/454  collaborative 
- [x] Rbn Bnj [Southern Summer](http://contradb.com/dances/449) http://contradb.com/dances/449  collaborative 
- [ ] Rn Weer [Just to See You Smile](http://contradb.com/dances/672) http://contradb.com/dances/672   
- [x] St Tper [ 40 Years of Penguin Pam](http://contradb.com/dances/74) http://contradb.com/dances/74   
153/608 dances updated

**Comment by cranhandler** [comment]
If it's not a huge burden, I would love the https://contradb.com/dances/431 to print as part of this list as well---then I can copy the list and send appropriate dances to their owners.

**Comment by dcmorse** [comment]
This is a list of all dances with heys. It includes dance 431 by _Mce Fest_ already! Is that what you wanted?

**Comment by dcmorse** [comment]
updated!

**Comment by cranhandler** [comment]
All owners (and null setting) emailed :)

**Comment by cranhandler** [comment]
Oddballs log:

'along the set' means ends and centers language doesn't really make sense
 Alo Jnak Jurassic Redheads http://contradb.com/dances/495 collaborative

**Comment by ibanner56** [comment]
I did my homework this time!

**Comment by dcmorse** [comment]
@dcmorse to contact R.W./Just to See You Smile. @cranhandler to handle the remaining straglers.

**Comment by dcmorse** [comment]
I repinged R.W./Just to See You Smile. @cranhandler can we resolve this issue? It's been in flight for 15 moths.

**Comment by cranhandler** [comment]
Granted.
