### ISSUE TITLE
allowed beats for heys

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#518]
12 beats is the correct number of beats for this "3/4 hey", but the 'allowed beats' validator is unhappy with it. 

![image](https://user-images.githubusercontent.com/16180173/46094238-0f823900-c17f-11e8-8ac4-c8f341c43662.png)

**Comment by dcmorse** [comment]
I'm gonna mark it a [1] for very loosey-goosey beats complaints on non-half, non-full heys.
