### ISSUE TITLE
Do si do 1½ in 8 beats is not valid

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#528]
Do si do 1 1/2 can only be done in 8 beats by the spriest of the spry. Suggest we give a beats validator error for it.

**Comment by dcmorse** [comment]
FYI this will invalidate about 40 dances. About 20 by user Don F. and about 10 by user Allison J.

**Comment by dcmorse** [comment]
Now do-si-dos < 1.5x per 8 beats are valid.
It was do-si-dos <= 1.5x per 8 beats were valid. 

I have not adjusted any dances or notified any users. I hope that natural processes will take care of that.
