### ISSUE TITLE
filter 'count' is a synonym for beats, and users can't find it

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#529]
proposed alternatives - and their objections
- `occurs` - but its basically a synonym for every filter
- `count occurrences` - long
- `repeat` - Allison thinks repeat > 0 means 2 occurrences
- `match count`
- `count matches`
- add a 'beats' filter, so that this becomes clearer! See #511

**Comment by dcmorse** [comment]
Hey @cranhandler, any of the options above (besides #511) is a [1], so let's pick one!

**Comment by cranhandler** [comment]
I choose 'occurs'!

**Comment by dcmorse** [comment]
Ach! That's the one that makes no sense to me, because it's means everything. All the searches are for things that 'occur'. 

- `number`  ⬳ <3
- `number of`

**Comment by cranhandler** [comment]
I can settle with 'number of'

**Comment by dcmorse** [comment]
![2](https://user-images.githubusercontent.com/10550086/48180203-312b2000-e2e8-11e8-9ac1-5a8c9307f989.png)
![1](https://user-images.githubusercontent.com/10550086/48180210-35efd400-e2e8-11e8-9ee8-b6ffe56233dd.png)

**Comment by dcmorse** [comment]
'number of' looks pretty good in the  drop-down menu, below, but as pictured in the UI above, it doesn't read as a sentence and so strikes a more discordant note.
![menu](https://user-images.githubusercontent.com/10550086/48199425-9818fb00-e321-11e8-88d8-142bccb78fb9.png)

**Comment by dcmorse** [comment]
reopened for discussion now that you can see the menu live. Close it if you're still okay with `number of`.

**Comment by dcmorse** [comment]
gonna change it to 'number' for lack of strongly held opinion on your part.
Going once...
Going twice...

**Comment by cranhandler** [comment]
> Clearer! Yes, “number of” doesn’t quite flow in a sentence, but works OK in the UI.

>I’m sorry is missed the discussion. “Happens” might have been a strong contender, but the team will have to stop fussing on minor stuff like this.

>Thanks for looping me back in. Makes me feel comments matter!

>\Bob

**Comment by dcmorse** [comment]
resolved by c53088f4cddb52332cb4dda8e4b578ec4a6b5660
