### ISSUE TITLE
Dances with a weird number of beats

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#530]
not necessarily broken, but probably worth looking at:

irb(main):027:0> Dance.all.to_a.select {|d| d.figures.map{|f| JSLibFigure.beats(f) }.sum != 64}.each {|d| puts "#{d.figures.map{|f| JSLibFigure.beats(f) }.sum} https://contradb.com/dances/#{d.id} #{d.title.inspect}"} ; nil
  Dance Load (9.1ms)  SELECT "dances".* FROM "dances"

BEATS | URL | TITLE
56 https://contradb.com/dances/717 "The Dancing Sailors"
118 https://contradb.com/dances/660 "stars wip"
68 https://contradb.com/dances/350 "A. O. 's No-No Software Testing"
62 https://contradb.com/dances/594 "Salmonella Evening"
60 https://contradb.com/dances/669 "Waving Wheat"
82 https://contradb.com/dances/645 "Wizard's Way"
88 https://contradb.com/dances/34 "[untitled]"
128 https://contradb.com/dances/142 "Moon Dance / Sun Dance"
62 https://contradb.com/dances/656 "Du Quoin Races"
60 https://contradb.com/dances/707 "ANTICI...PATION"
68 https://contradb.com/dances/283 "Unexpected Pleasure"
128 https://contradb.com/dances/357 "Alternating Corners"
62 https://contradb.com/dances/211 "Untitled"
58 https://contradb.com/dances/535 "Trip to Wilson"
128 https://contradb.com/dances/368 "Turning In Turn"
62 https://contradb.com/dances/524 "Gaye's Groove"
60 https://contradb.com/dances/553 "Attleboro Reel"
128 https://contradb.com/dances/552 "Labor of Love"
60 https://contradb.com/dances/554 "Celebration"
60 https://contradb.com/dances/555 "Circle of Fun"
80 https://contradb.com/dances/557 "Virginia Reel"
58 https://contradb.com/dances/560 "Peak Bagger"
66 https://contradb.com/dances/136 "Midwest Folklore"
68 https://contradb.com/dances/499 "Parkay: Ode to a Dance Floor"
72 https://contradb.com/dances/568 "Dive for the Dolphin"
62 https://contradb.com/dances/348 "Not Quite Fifty Software Testing"
72 https://contradb.com/dances/86 "Truffles for Breakfast"
69 https://contradb.com/dances/68 "Across Nottingham A"
68 https://contradb.com/dances/634 "Firefly Pedicabs"
96 https://contradb.com/dances/74 " 40 Years of Penguin Pam"
74 https://contradb.com/dances/494 "Twirling At The Altar"
96 https://contradb.com/dances/422 "The Menagerie"
112 https://contradb.com/dances/715 "Would You Do It for $20?"
96 https://contradb.com/dances/76 " 40 Years of Penguin Pam refactored"

**Comment by cranhandler** [comment]
**Dances with "Ones then Twos"**


**Slip-jigs**

**Other reason??**
(private) https://contradb.com/dances/594 (pass through needs nudged up to 4 beats) 

**Incomplete/broken dance**
(private) https://contradb.com/dances/660 
(private) https://contradb.com/dances/350

**Comment by dcmorse** [comment]
Here's 39 dances using the pattern

- circle 3 places (6)
- pass through (2)

That's probably why pass-through's default is 2 beats. 

![circle-pass-through](https://user-images.githubusercontent.com/10550086/47299259-6b55ab80-d5df-11e8-9fa5-a25b493b625c.png)

**Comment by dcmorse** [comment]
Adding this to Core/In Progress, because it appears to be in progress.

**Comment by dcmorse** [comment]
closed due to inactivity
