### ISSUE TITLE
dialect bug

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#539]
Logged in as myself. Dialect is set to Larks & Ravens by the default radio button. 

https://contradb.com/dances/561

in the second line of the A1, is showing 'ladle' where it should be showing 'raven' in view mode. It corrects itself in edit mode. Unsure what to do. 

![image](https://user-images.githubusercontent.com/16180173/48958329-d3234d00-ef23-11e8-8127-208bd25cee0e.png)

![image](https://user-images.githubusercontent.com/16180173/48958347-f2ba7580-ef23-11e8-8b9f-8793a8c99ac1.png)

**Comment by dcmorse** [comment]
A workaround would be to copy the dance and replace it with a custom.

**Comment by dcmorse** [comment]
We do some special in-figure processing of text fields for custom, that we don't do for turn alone (and maybe not for other text fields - should check). Adding that special processing should fix this.
