### ISSUE TITLE
Search validated dances only

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#544]
Once validation tags are open, allow to search 'only dances which have been validated >=1 time'

**Comment by dcmorse** [comment]
This [4] is for a simple toggle on the existing search page.

**Comment by cranhandler** [comment]
But is it BETTER to make the change when we make the big changes to search?

**Comment by dcmorse** [comment]
It's less overall work to wait for the big search rewrite, but if you want this [4] now, then that's an option for you.

**Comment by cranhandler** [comment]
Let's do it all in one swoop.

But, after we handle any outstanding bugs, I think the search revamp is a
good next swoop.

**Comment by dcmorse** [comment]
This is pretty much addressed by #573. There are problems with that PR, but I prefer to break them into different stories.
