### ISSUE TITLE
simple dance issue reporting

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#550]
On the side panel for every dance, there's a heading:

```
REPORT ISSUE
adminisaur@emailaddress.com
```
It's always there, if they're logged in, or not, and you deal with the spam with your spam filter.

**Comment by cranhandler** [comment]
Good plan.

Pardon brevity; sent by smartphone.

**Comment by dcmorse** [comment]
I'm moving this to 'ready to code'!
