### ISSUE TITLE
Unlisted, or link-shared, dance publicity setting

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#570]
Request from User 14:

> Right now ContraDB only has two states for a dance: published and private. If a dance is published, everyone can see it. If a dance is private, only the writer can see it. I think there should be either a third state or another option for private dances which allows you to share it with others without making it open to public viewing. That way if you have a dance that's a WIP or which you don't want published but call somewhere and want to share with someone you can do so using ContraDB.

I replied, suggesting:

> This is a good idea. Maybe we'd call the status "link only" ? 

> Until we get a chance to build it, the current workaround would be "create a dummy account named MyName WIP or something, with a password you can share with your friend"? But I see how this is not long-term ideal. 
>We do also have people label WIP dances by making the title "A Barnful of Boulders DO NOT CALL YET" or similar.

**Comment by dcmorse** [comment]
#588   implemented this
