### ISSUE TITLE
Replacing publish/private language with "sharing" language in account notifications

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#582]
Regarding https://contradb.com/users/edit (must be logged in)

![published lingo](https://user-images.githubusercontent.com/10550086/67163868-e314fe00-f339-11e9-9f63-2c5a68311503.png)

**Comment by cranhandler** [comment]
If an issue is noticed in a dance I have shared, moderators should...
collaborative - edit or reduce sharing permissions for the dance, emailing me the original text
owner - email me, then if I don't respond within 2 weeks reduce sharing permissions for the dance
hermit - reduce sharing permissions for the dance, do not contact me
