### ISSUE TITLE
compound searches don't behave right with back button in chrome 79

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#611]
- With Google Chrome browser, go to contradb.com
- From the search select that starts as `figure`, select `and`. 
- Visit some dance page
- click 'back'

You get this:
![s1](https://user-images.githubusercontent.com/10550086/71787322-e4ba9d80-2fdb-11ea-865c-0b20b751773f.png)
Was expecting this:
![Screenshot from 2020-01-05 16-53-05](https://user-images.githubusercontent.com/10550086/71787324-edab6f00-2fdb-11ea-80a1-2ddf2b2d0594.png)

We have 3 related failing tests in our test suite already. Just run them on a machine with chrome 79.

**Comment by cranhandler** [comment]
This is bumped by a user,

> If one does a search for some dances, then clicks on a specific dance,  back button does not return to search results, but rather to all dances, focing one to re-do the search.

**Comment by dcmorse** [comment]
welcome.js
```
  if ("" === $("#figure-query-buffer").val()) {
    // first time visiting the page, e.g. not returning via browser 'back' button
    ...
  } else {
    // back button pressed -> rebuilding the dom from figure query buffer
    ...
  }
```

This code is taking the 'then' branch at the critical time when it should take the 'else' branch. I'm not sure how else to test the value of a text field, other than, well, testing the value of a test field.

**Comment by dcmorse** [comment]
I'm going to move the state from hidden text fields to session storage. That appears to be what it's for.

**Comment by dcmorse** [comment]
That worked okay, but there's another problem:
Some jerkweed (no doubt me) is somehwhere setting the value of subtrees to nil. 
I'm having a hard time figuring out where that state modification is happening. 
I stuffed the wip (chock-full of debugging cookies and session-storage) in the branch `back-button`. 
I'm resuming feature work with this unresolved, since this will go away when the new search interface ships.
