### ISSUE TITLE
search by verified

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#618]
Add controls to search only for verified dances by default, with additional controls for searching dances that aren't verified, or that are verified by the current user. 

![verified](https://user-images.githubusercontent.com/10550086/73593807-9d85d680-44cd-11ea-8bfc-14346d2d46e6.png)

`broken` isn't a thing, so we're removing that. 

That leaves the 3 remaining checkboxes. I'm expanding them to 4 for the sake of completeness:

- [x] verified
- [ ] unverified
- [ ] verified by me
- [ ] unverified by me

## Search Fewer Dances
The number of dances searched will drop to about 200 with this new checkbox checking. Of course, this is not yet the front page, so user impact will be limited ... for now. 

[Edit: And I just realized that you wanted the default to be 'verified by me' instead of 'verified' ... in which case the number of dances searched would drop to zero for new users and not-logged-in-users. Let's reconsider!]

## Checkboxes
Note that these are _checkboxes_ and not _radio buttons_ - you can search for `verified` and `unverified` at the same time, which is equivalent to what you get today: just searching all dances. You can, I suppose, uncheck all the boxes and search for nothing. If you search for both `verified` and `verified by me`, you get the same as if you'd only searched for `verified`. Similarly with `unverified` and `unverified by me`. 

## Users who aren't logged in
Choose one of these options or come up with something else...

### redirect them to login page
cons: will currently clear their search query. Which is trivial to reconstruct at this point.

### disable the check boxes and provide a tooltip hinting they could log in.
cons: tooltips aren't a thing on phones. 

### hide the checkboxes
cons: doesn't advertise the advantage of logging in

**Comment by dcmorse** [comment]
I'm leaning towards "disable the checkboxes and provide a tooltip hinting they could log in".

**Comment by dcmorse** [comment]
![checkboxes](https://user-images.githubusercontent.com/10550086/73715574-fde96380-46d9-11ea-8f0f-76dd3dbcd337.png)

**Comment by cranhandler** [comment]
Here's Github's approach yo "mobile won't show tooltips". I would suggest grayed out with one-a-these. This doesn't show til they hit the + in front of verified or tagged, though


![77D69195-588F-482C-AD3A-0203A32BB82B](https://user-images.githubusercontent.com/16180173/73733836-46b51280-4702-11ea-92b0-29b72faa2cdf.jpeg)

**Comment by dcmorse** [comment]
I'm not sure what I'm seeing here. You're saying if they click on an image, then an absolutely positioned additional header comes down that says 
```
[(!) Open] Search by Verified 
#618 dcmorse opened this issue 3 days ago
``` 
?

**Comment by dcmorse** [comment]
A big absolutely-positioned tooltip implementation scares me. It's hard, and it's still kicks the can on the road on the question of "where are the users' eyes?". 

On mobile we want minimal clutter. So I think on mobile we simply don't display "verified by me" if they're not logged in. It's spreading our efforts too thinly to try to induce them to log in on such a small screen.

**Comment by dcmorse** [comment]
Similarly, on mobile, even if they are logged in, I wonder if we should even display the very marginal "not verified by me". 

I guess there's kinda a larger idea here of "what are you here for?"
- find a dance to call right now
- researching what dances are out there
and the answers to these check boxes kinda depend on that ur-question.

**Comment by dcmorse** [comment]
deployed.
