### ISSUE TITLE
shared ezfilter

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#620]
Below the "Verified" ezfilter, add a "Shared" ezfilter:

### Shared
- [x] shared
- [ ] sketchbooks
- [ ] private*
-------------
- [ ] anything by me

### Shared
- [x] shared
- [ ] sketchbooks
-----------
- [x] anything by me
-----------
- [ ] omniscient

"by me" is disabled/hidden when no user is logged in, as in #618. 
Similarly, "omnicient" is disabled/hidden when the user is not an admin. 

(this is part of the #563 story)

**Comment by dcmorse** [comment]
Gonna split `by me` out into it's own radio, which only shows when logged in:

### User
◉ anyone
○ me

**Comment by dcmorse** [comment]
An unfortunate story, starring me.

To ensure that the new "anything by me" checkbox was working properly, I created a private dance. 

I had 'anything by me' checked, but I couldn't see it. I made extra sure that if 'anything by me' was checked, then it didn't matter if the dance was in the sketchbook or private or whatever. It should display. 

Only it wasn't there. 

I kept debugging. I wasn't reproducing it in automated tests. What was going on here?

The answer was: the private dance wasn't tagged as verified. :(

So how do these various heading groups interact? Are they combined with 'and' or with 'or'? It *must* be 'and', right? I don't want to search for "Cary Ravitz" in the choreographer field, and select "verified" dances, and get a bunch of dances that are verified and not by Cary Ravitz. 

But my expectation for "by me" breaks that mold and now I feel confused and demoralized about coming up with a coherent vision for the ez filters. 


Probably dumb ideas for a solution:

1) Promote 'only by me' to its own section (users will have to deal with the same confusion I felt about verified tags, and we'll also have to add a 'search your private dances' checkbox). 
2) Remove 'only by me' from the UI for now

**Comment by dcmorse** [comment]
## Option One: remove the 'Shared' section entirely
Search all dances by default (published dances and dances by me), but subject still to what the user checked in the 'Verified' section, which is by default only 'verified'. So presumably their private dances haven't been verified and thus won't show up. Other people's sketchbooks would not be searchable. 

*Pros:* at least this focuses the user's attention on only one section that could be maliciously hiding their dances. 

*Cons:* there is no way to opt in to search others' sketchbooks. Sketchbooks become a more fringe idea. 

## Option Two: a dumb 'Shared' section
It has only 'shared', 'sketchbook', and 'off' entries. 'shared' is the only one checked by default. To actually see your brainfart dances, you'd have to do two things: check boxes in this section, and /somehow remember/ to check the 'not verified' checkbox in verified. I'm pessimistic.

*Cons* It's a setting that often will need to be thought about then overlooked. On the occassions where it's needed, it requires also interacting with another section - verified - to get it to work. This forces the user to think. 

## Option 3: search both verified and not-verified dances by default. 
With this more historical approach to verification, then the smarter checkboxes at the head of this issue begin to make sense again (shared/sketchbooks/anything by me). The user is never two or more clicks away from a filter that doesn't do what the labels of the checkboxes say. However, the cost of this is that at zero clicks you see unverified dances. Hmmm.

**Comment by dcmorse** [comment]
## Option 4: the original plan, with a warning light
the options at the root of this issue: (shared/sketchbook/anything by me), but when 'sketchbook' or 'anything by me' is checked, and 'not verified' isn't checked, a warning light comes on right in the 'Shared' section saying "only seeing verified dances".

**Comment by cranhandler** [comment]
I vote for Option 4.

**Comment by dcmorse** [comment]
### Making it so, captain!

Couple-a tweaks under consideration:
-`anything by me` is not checked by default so that people don't have to see a scary warning message on their first arrival at the page. 
- replace "omniscient" with "private". It's still only visible to admins, because regular Janes can see their private dances with `anything by me`.

**Comment by dcmorse** [comment]
Closing for now. We can reopen in a new card once we've paused to gather feedback.

**Comment by cranhandler** [comment]
I approve these tweaks.
