### ISSUE TITLE
formation ezfilter

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#621]
### Formation

- [x] improper
- [x] Becket
- [x] proper
- [x] everything else

## Long term plan:
Adopt taxonomy in #493 as detailed in the [roadmap](https://github.com/contradb/contra/projects/6)

## Archival version of this card:

![formation](https://user-images.githubusercontent.com/10550086/73848727-46924100-47ee-11ea-85ca-d01c9e65f1fc.png)

Expand to be replaced by something not-a-checkbox. A bootstrap toggle? A '▶' toggler?
And the contents of that menu also to be defined. 

(this is part of #563)

**Comment by dcmorse** [comment]
I think we need to clarify what these checkboxes achieve. This story can be quick and useful if we pick good things to have checkboxes for. Or it can be a major overhaul of how we store formations, and last a couple of months. For this story, I favor the latter approach! So what should we have checkboxes for? Here's the current formations in the db:
```
673 improper
352 Becket
 93 Becket ccw
 33 proper
 29 Contra, duple improper
 18 Improper
 16 Becket cw
 13 four face four
 13 indecent
  9 square dance
  8 circle mixer
  5 improper or proper
  5 becket
  4 Duple Improper
  4 scatter mixer
  4 Sicilian circle
  4 triplet
  4 progressed improper
  3 Proper
  2 Becket  cw
  2 Becket CW
  2 Circle Mixer
  2 improper, but with 1's below 2's
  2 Becket, Double Progression
  2 circle
  2 improper, double progression
  2 three-face-three
  2 Sicilian Circle
  1 Becket double progression
  1 improper (4cpl)
  1 Contra, duple PROPER
  1 improper then L1 and G2 swap places
  1 Progressed Improper (wait out like Becket)
  1 Contra, becket (cw)
  1 Contra, becket formation (progress cw)
  1 Contra, Becket formation, ccw
  1 Contra, becket
  1 Contra duple improper
  1 triplet, proper
  1 square dance break
  1 Triplet, 1s and 2s improper
  1 Beckett CCW
  1 Beckett
  1 Becket  ccw
  1 duple minor
  1 Imroper
  1 Becket men in center left hands, right hand to partner in ocean of four
  1 Becketa
  1 Becket CW, double progression
  1 sawtooth cw
  1 indecent becket
  1 sawtooth CW
  1 Progressed Improper
  1 Becket, indecent
  1 cross contra
  1 All Improper
  1 Duple improper longways 
  1 Sawtooth Becket
  1 triple minor, triad formation
  1 Tempest
  1 Contra, becket formation, double progression, cw
  1 cross contra - improper then ladle one and ladle two trade places
  1 improper - double progression
  1 Becket 
  1 improper - waltz tempo
  1 improper, reverse progression
  1 proper, ladles traded
  1  improper
  1 triple minor
  1 cross contra - improper then ladle one and gentlespoon two  trade places
  1 improper reverse progression
  1 triple proper
  1 three face three
  1 four couple square
  1 improper - double Progression
  1 four couple longways set
  1 Triplet
  1 improper 
  1 contra mixer
  1 Becket clockwise
  1 Becket   double progression
```

**Comment by dcmorse** [comment]
...and here's how the current formation filter handles it:
![formation](https://user-images.githubusercontent.com/10550086/73850853-26648100-47f2-11ea-97a7-4cc44bb3a532.png)

**Comment by jmdyck** [comment]
(See also #493.)

**Comment by dcmorse** [comment]
minimalist proposal:

- [x] improper
- [x] Becket *
- [x] everything else

**Comment by cranhandler** [comment]
I have a strong feeling here and I'm afraid you will disagree with it.

My proposal would be 

- [ ] d. improper
- [ ] Becket*
- [ ] proper
- [ ] expand the list 


Expanding the list appears the full list of possible formations, which, and this is where I expect pushback but I think it's the right thing--

is the complete list of formations that jmdyck uses in The Caller's Box.  I think this is correct because it gives us the complete set of possibilities, and keeps contra terminology consistent across the two major choreography repositories---while remaining simple on the surface for basic searchers. 


We don't need to include progression in formation (so becket* is becketcw and becket ccw but doesn't care whether it's double or single progression) because that's handled elsewhere.

**Comment by dcmorse** [comment]
The top of the issue has been updated with the results of our textstorm.
